import type { Problem } from "./types";

export const PROBLEMS: Problem[] = [
  // ============= LEVEL 0 — BASICS (5) =============
  {
    id: "p1",
    title: "Select all users",
    level: 0,
    difficulty: 1,
    topics: ["SELECT"],
    goal: "Learn the basic SELECT * FROM table syntax.",
    problem: "Return all columns and all rows from the `users` table.",
    starter_sql: "SELECT * FROM users;",
    solution: "SELECT * FROM users;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["Use SELECT *", "FROM users"],
    explanation: "SELECT * returns every column. With no WHERE clause, every row is returned.",
    estimated_time_min: 1,
  },
  {
    id: "p2",
    title: "All product names",
    level: 0,
    difficulty: 1,
    topics: ["SELECT"],
    goal: "Project a single column.",
    problem: "Return only the `name` column from the `products` table.",
    starter_sql: "SELECT  FROM products;",
    solution: "SELECT name FROM products;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["Replace * with the column name"],
    explanation: "Listing column names instead of * returns only those columns.",
    estimated_time_min: 1,
  },
  {
    id: "p3",
    title: "Distinct categories",
    level: 0,
    difficulty: 1,
    topics: ["DISTINCT"],
    goal: "Remove duplicate rows.",
    problem: "Return each unique product `category` once.",
    starter_sql: "SELECT category FROM products;",
    solution: "SELECT DISTINCT category FROM products;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["DISTINCT removes duplicates"],
    explanation: "DISTINCT collapses identical rows in the result.",
    estimated_time_min: 1,
  },
  {
    id: "p4",
    title: "User name and email",
    level: 0,
    difficulty: 1,
    topics: ["SELECT"],
    goal: "Project multiple columns.",
    problem: "Return `name` and `email` from `users`.",
    starter_sql: "SELECT  FROM users;",
    solution: "SELECT name, email FROM users;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["Separate column names with commas"],
    explanation: "Multiple columns are listed with commas.",
    estimated_time_min: 1,
  },
  {
    id: "p5",
    title: "Count all orders",
    level: 0,
    difficulty: 1,
    topics: ["COUNT"],
    goal: "Use a basic aggregate.",
    problem: "Return the total number of rows in `orders`.",
    starter_sql: "SELECT  FROM orders;",
    solution: "SELECT COUNT(*) FROM orders;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["COUNT(*) counts all rows"],
    explanation: "COUNT(*) is the most common aggregate; it counts every row.",
    estimated_time_min: 1,
  },

  // ============= LEVEL 1 — FILTERING (10) =============
  {
    id: "p6",
    title: "Expensive products",
    level: 1,
    difficulty: 1,
    topics: ["WHERE"],
    goal: "Filter rows by a numeric condition.",
    problem: "Return all products with a price greater than 100.",
    starter_sql: "SELECT * FROM products WHERE ;",
    solution: "SELECT * FROM products WHERE price > 100;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["Use the WHERE clause", "price > 100"],
    explanation: "WHERE filters rows that match a condition.",
    estimated_time_min: 2,
  },
  {
    id: "p7",
    title: "Recent users",
    level: 1,
    difficulty: 1,
    topics: ["WHERE"],
    goal: "Filter on a date column.",
    problem: "Return users created after 2023-02-01.",
    starter_sql: "SELECT * FROM users WHERE ;",
    solution: "SELECT * FROM users WHERE created_at > '2023-02-01';",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["Dates in SQLite are compared as strings in ISO format"],
    explanation: "ISO-formatted dates ('YYYY-MM-DD') compare correctly as strings.",
    estimated_time_min: 2,
  },
  {
    id: "p8",
    title: "Electronics only",
    level: 1,
    difficulty: 1,
    topics: ["WHERE"],
    goal: "Filter by an exact text match.",
    problem: "Return all products in the 'Electronics' category.",
    starter_sql: "SELECT * FROM products WHERE ;",
    solution: "SELECT * FROM products WHERE category = 'Electronics';",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["Use single quotes for text"],
    explanation: "Use single quotes for string literals in SQL.",
    estimated_time_min: 2,
  },
  {
    id: "p9",
    title: "Pending orders",
    level: 1,
    difficulty: 1,
    topics: ["WHERE"],
    goal: "Filter by status.",
    problem: "Return all orders with status 'pending'.",
    starter_sql: "SELECT * FROM orders WHERE ;",
    solution: "SELECT * FROM orders WHERE status = 'pending';",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["status = 'pending'"],
    explanation: "Equality on text columns is a frequent filter.",
    estimated_time_min: 2,
  },
  {
    id: "p10",
    title: "Multiple categories",
    level: 1,
    difficulty: 2,
    topics: ["IN"],
    goal: "Filter for multiple allowed values.",
    problem: "Return products in either 'Electronics' or 'Furniture'.",
    starter_sql: "SELECT * FROM products WHERE ;",
    solution: "SELECT * FROM products WHERE category IN ('Electronics', 'Furniture');",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["IN ('a', 'b') is shorter than two ORs"],
    explanation: "IN checks membership in a list of values.",
    estimated_time_min: 2,
  },
  {
    id: "p11",
    title: "Names starting with A",
    level: 1,
    difficulty: 2,
    topics: ["LIKE"],
    goal: "Pattern match on text.",
    problem: "Return users whose `name` starts with the letter 'A'.",
    starter_sql: "SELECT * FROM users WHERE ;",
    solution: "SELECT * FROM users WHERE name LIKE 'A%';",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["LIKE 'A%'", "% means any characters"],
    explanation: "LIKE supports wildcards: % matches any string, _ matches one character.",
    estimated_time_min: 2,
  },
  {
    id: "p12",
    title: "Price range",
    level: 1,
    difficulty: 2,
    topics: ["BETWEEN"],
    goal: "Filter on a numeric range.",
    problem: "Return products with a price between 100 and 500 (inclusive).",
    starter_sql: "SELECT * FROM products WHERE ;",
    solution: "SELECT * FROM products WHERE price BETWEEN 100 AND 500;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["BETWEEN x AND y is inclusive"],
    explanation: "BETWEEN is inclusive on both bounds.",
    estimated_time_min: 2,
  },
  {
    id: "p13",
    title: "Sorted by price",
    level: 1,
    difficulty: 2,
    topics: ["ORDER BY"],
    goal: "Order results.",
    problem: "Return all products sorted by price descending.",
    starter_sql: "SELECT * FROM products ORDER BY ;",
    solution: "SELECT * FROM products ORDER BY price DESC;",
    validation: { ignore_order: false, ignore_column_names: true },
    hints: ["ORDER BY price DESC"],
    explanation: "ORDER BY sorts rows; DESC = descending. Order matters here.",
    estimated_time_min: 2,
  },
  {
    id: "p14",
    title: "Top 3 cheapest products",
    level: 1,
    difficulty: 2,
    topics: ["ORDER BY", "LIMIT"],
    goal: "Combine sort and limit.",
    problem: "Return the 3 cheapest products.",
    starter_sql: "SELECT * FROM products ORDER BY  LIMIT ;",
    solution: "SELECT * FROM products ORDER BY price ASC LIMIT 3;",
    validation: { ignore_order: false, ignore_column_names: true },
    hints: ["ORDER BY price ASC", "LIMIT 3"],
    explanation: "Combine ORDER BY and LIMIT for top-N queries.",
    estimated_time_min: 2,
  },
  {
    id: "p15",
    title: "Out of stock products",
    level: 1,
    difficulty: 2,
    topics: ["WHERE"],
    goal: "Filter on a numeric equality.",
    problem: "Return products where `stock` is less than 20.",
    starter_sql: "SELECT * FROM products WHERE ;",
    solution: "SELECT * FROM products WHERE stock < 20;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["stock < 20"],
    explanation: "Numeric comparison filters work just like other conditions.",
    estimated_time_min: 2,
  },

  // ============= LEVEL 2 — JOINS (15) =============
  {
    id: "p16",
    title: "Orders with user names",
    level: 2,
    difficulty: 2,
    topics: ["JOIN"],
    goal: "Join two tables on a foreign key.",
    problem: "Return each order's id together with the customer's name.",
    starter_sql: "SELECT o.id, u.name FROM orders o JOIN users u ON ;",
    solution: "SELECT o.id, u.name FROM orders o JOIN users u ON o.user_id = u.id;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["Join on orders.user_id = users.id"],
    explanation: "INNER JOIN matches rows where the join condition is true.",
    estimated_time_min: 3,
  },
  {
    id: "p17",
    title: "Order items with product names",
    level: 2,
    difficulty: 2,
    topics: ["JOIN"],
    goal: "Join order_items to products.",
    problem: "Return order_item id and the product's name for every order item.",
    starter_sql: "SELECT oi.id, p.name FROM order_items oi JOIN products p ON ;",
    solution: "SELECT oi.id, p.name FROM order_items oi JOIN products p ON oi.product_id = p.id;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["Join on product_id = products.id"],
    explanation: "Joins let us follow foreign keys to enrich rows.",
    estimated_time_min: 3,
  },
  {
    id: "p18",
    title: "Users with no orders",
    level: 2,
    difficulty: 3,
    topics: ["LEFT JOIN", "NULL"],
    goal: "Find missing relations using LEFT JOIN + IS NULL.",
    problem: "Return users (id, name) who have never placed an order.",
    starter_sql: "SELECT u.id, u.name FROM users u LEFT JOIN orders o ON  WHERE ;",
    solution: "SELECT u.id, u.name FROM users u LEFT JOIN orders o ON o.user_id = u.id WHERE o.id IS NULL;",
    alt_solutions: ["SELECT id, name FROM users WHERE id NOT IN (SELECT user_id FROM orders);"],
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["LEFT JOIN keeps all users", "WHERE o.id IS NULL keeps unmatched rows"],
    explanation: "LEFT JOIN + IS NULL is the classic 'anti-join' pattern.",
    estimated_time_min: 4,
  },
  {
    id: "p19",
    title: "Order totals from items",
    level: 2,
    difficulty: 3,
    topics: ["JOIN", "GROUP BY", "SUM"],
    goal: "Aggregate after joining.",
    problem: "For each order id, return the total value (sum of quantity * price across order_items).",
    starter_sql: "SELECT order_id, SUM(quantity * price) AS total FROM order_items GROUP BY order_id;",
    solution: "SELECT order_id, SUM(quantity * price) AS total FROM order_items GROUP BY order_id;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["SUM(quantity * price)", "GROUP BY order_id"],
    explanation: "Aggregates collapse groups; GROUP BY defines the group.",
    estimated_time_min: 3,
  },
  {
    id: "p20",
    title: "Orders + user + payment",
    level: 2,
    difficulty: 3,
    topics: ["JOIN"],
    goal: "Join three tables.",
    problem: "Return order id, user name, and payment status for every order that has a payment.",
    starter_sql: "SELECT o.id, u.name, p.status FROM orders o JOIN users u ON o.user_id = u.id JOIN payments p ON p.order_id = o.id;",
    solution: "SELECT o.id, u.name, p.status FROM orders o JOIN users u ON o.user_id = u.id JOIN payments p ON p.order_id = o.id;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["Chain joins: orders -> users, orders -> payments"],
    explanation: "Multiple JOINs can be chained as long as you keep aliases clear.",
    estimated_time_min: 3,
  },
  {
    id: "p21",
    title: "Products never ordered",
    level: 2,
    difficulty: 3,
    topics: ["LEFT JOIN", "NULL"],
    goal: "Anti-join on the products side.",
    problem: "Return products (id, name) that never appear in any order_item.",
    starter_sql: "SELECT p.id, p.name FROM products p LEFT JOIN order_items oi ON  WHERE ;",
    solution: "SELECT p.id, p.name FROM products p LEFT JOIN order_items oi ON oi.product_id = p.id WHERE oi.id IS NULL;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["LEFT JOIN order_items, then filter IS NULL"],
    explanation: "Same anti-join pattern, applied from the products side.",
    estimated_time_min: 3,
  },
  {
    id: "p22",
    title: "Completed orders with names",
    level: 2,
    difficulty: 2,
    topics: ["JOIN", "WHERE"],
    goal: "Combine join and filter.",
    problem: "Return order id and user name for orders with status 'completed'.",
    starter_sql: "SELECT o.id, u.name FROM orders o JOIN users u ON o.user_id = u.id WHERE ;",
    solution: "SELECT o.id, u.name FROM orders o JOIN users u ON o.user_id = u.id WHERE o.status = 'completed';",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["WHERE o.status = 'completed'"],
    explanation: "WHERE filters apply after the join is computed.",
    estimated_time_min: 2,
  },
  {
    id: "p23",
    title: "Order line details",
    level: 2,
    difficulty: 3,
    topics: ["JOIN"],
    goal: "Three-way join across order, item and product.",
    problem: "Return order_id, product name and quantity for every order_item.",
    starter_sql: "SELECT oi.order_id, p.name, oi.quantity FROM order_items oi JOIN products p ON p.id = oi.product_id;",
    solution: "SELECT oi.order_id, p.name, oi.quantity FROM order_items oi JOIN products p ON p.id = oi.product_id;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["Join order_items to products"],
    explanation: "Join the bridge table (order_items) to a dimension (products).",
    estimated_time_min: 3,
  },
  {
    id: "p24",
    title: "Users who paid with card",
    level: 2,
    difficulty: 3,
    topics: ["JOIN", "DISTINCT"],
    goal: "Distinct users via multi-join.",
    problem: "Return distinct user names who have at least one payment with method 'card'.",
    starter_sql: "SELECT DISTINCT u.name FROM users u JOIN orders o ON o.user_id = u.id JOIN payments p ON p.order_id = o.id WHERE p.method = 'card';",
    solution: "SELECT DISTINCT u.name FROM users u JOIN orders o ON o.user_id = u.id JOIN payments p ON p.order_id = o.id WHERE p.method = 'card';",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["DISTINCT to avoid duplicates from multiple orders"],
    explanation: "DISTINCT is necessary when joins can multiply rows per user.",
    estimated_time_min: 3,
  },
  {
    id: "p25",
    title: "Orders without payments",
    level: 2,
    difficulty: 3,
    topics: ["LEFT JOIN", "NULL"],
    goal: "Find orders missing a payment record.",
    problem: "Return orders (id) that have no row in `payments`.",
    starter_sql: "SELECT o.id FROM orders o LEFT JOIN payments p ON  WHERE ;",
    solution: "SELECT o.id FROM orders o LEFT JOIN payments p ON p.order_id = o.id WHERE p.id IS NULL;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["LEFT JOIN payments, IS NULL"],
    explanation: "Anti-join again — useful for data quality checks.",
    estimated_time_min: 3,
  },
  {
    id: "p26",
    title: "User + order count (zero-friendly)",
    level: 2,
    difficulty: 3,
    topics: ["LEFT JOIN", "GROUP BY", "COUNT"],
    goal: "Count children including users with zero.",
    problem: "Return each user's name and the number of orders they have. Users with no orders should appear with 0.",
    starter_sql: "SELECT u.name, COUNT(o.id) AS order_count FROM users u LEFT JOIN orders o ON o.user_id = u.id GROUP BY u.name;",
    solution: "SELECT u.name, COUNT(o.id) AS order_count FROM users u LEFT JOIN orders o ON o.user_id = u.id GROUP BY u.name;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["COUNT(o.id), not COUNT(*) — to count NULLs as 0"],
    explanation: "COUNT ignores NULLs, so COUNT(o.id) gives 0 for unmatched left rows.",
    estimated_time_min: 4,
  },
  {
    id: "p27",
    title: "Self-info: products and their category peers",
    level: 2,
    difficulty: 3,
    topics: ["JOIN", "self-join"],
    goal: "Self-join a table.",
    problem: "Return pairs of distinct product names that share the same category. Each pair should appear once (a.id < b.id).",
    starter_sql: "SELECT a.name, b.name FROM products a JOIN products b ON a.category = b.category AND a.id < b.id;",
    solution: "SELECT a.name, b.name FROM products a JOIN products b ON a.category = b.category AND a.id < b.id;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["Join products to itself", "Use a.id < b.id to avoid duplicates"],
    explanation: "Self-joins relate rows from the same table.",
    estimated_time_min: 4,
  },
  {
    id: "p28",
    title: "Refunded orders + user",
    level: 2,
    difficulty: 2,
    topics: ["JOIN", "WHERE"],
    goal: "Filter by joined column.",
    problem: "Return user names who have at least one payment with status 'refunded'.",
    starter_sql: "SELECT DISTINCT u.name FROM users u JOIN orders o ON o.user_id = u.id JOIN payments p ON p.order_id = o.id WHERE p.status = 'refunded';",
    solution: "SELECT DISTINCT u.name FROM users u JOIN orders o ON o.user_id = u.id JOIN payments p ON p.order_id = o.id WHERE p.status = 'refunded';",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["WHERE on payment status"],
    explanation: "Filter conditions can target columns from any joined table.",
    estimated_time_min: 3,
  },
  {
    id: "p29",
    title: "All orders with optional payment",
    level: 2,
    difficulty: 3,
    topics: ["LEFT JOIN"],
    goal: "Include rows even when the right side is missing.",
    problem: "Return order id and payment amount for every order. If no payment exists, amount should be NULL.",
    starter_sql: "SELECT o.id, p.amount FROM orders o LEFT JOIN payments p ON p.order_id = o.id;",
    solution: "SELECT o.id, p.amount FROM orders o LEFT JOIN payments p ON p.order_id = o.id;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["LEFT JOIN keeps all rows from orders"],
    explanation: "LEFT JOIN preserves left-side rows; right side becomes NULL when missing.",
    estimated_time_min: 3,
  },
  {
    id: "p30",
    title: "Items per order",
    level: 2,
    difficulty: 3,
    topics: ["JOIN", "GROUP BY", "SUM"],
    goal: "Aggregate joined data.",
    problem: "Return order id and the total quantity of items in that order.",
    starter_sql: "SELECT order_id, SUM(quantity) AS total_qty FROM order_items GROUP BY order_id;",
    solution: "SELECT order_id, SUM(quantity) AS total_qty FROM order_items GROUP BY order_id;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["SUM(quantity) GROUP BY order_id"],
    explanation: "Standard aggregation grouped by the order key.",
    estimated_time_min: 3,
  },

  // ============= LEVEL 3 — AGGREGATION (10) =============
  {
    id: "p31",
    title: "Total user count",
    level: 3,
    difficulty: 1,
    topics: ["COUNT"],
    goal: "Single aggregate.",
    problem: "Return the total number of users.",
    starter_sql: "SELECT COUNT(*) FROM users;",
    solution: "SELECT COUNT(*) FROM users;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["COUNT(*)"],
    explanation: "COUNT(*) returns one row with the total.",
    estimated_time_min: 1,
  },
  {
    id: "p32",
    title: "Total revenue paid",
    level: 3,
    difficulty: 2,
    topics: ["SUM", "WHERE"],
    goal: "Aggregate with a filter.",
    problem: "Return the total amount across all payments where status = 'paid'.",
    starter_sql: "SELECT SUM(amount) FROM payments WHERE ;",
    solution: "SELECT SUM(amount) FROM payments WHERE status = 'paid';",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["SUM(amount)", "filter to status='paid'"],
    explanation: "WHERE applies before aggregation.",
    estimated_time_min: 2,
  },
  {
    id: "p33",
    title: "Average product price",
    level: 3,
    difficulty: 1,
    topics: ["AVG"],
    goal: "Compute an average.",
    problem: "Return the average price of all products.",
    starter_sql: "SELECT AVG(price) FROM products;",
    solution: "SELECT AVG(price) FROM products;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["AVG(price)"],
    explanation: "AVG ignores NULLs and returns a numeric average.",
    estimated_time_min: 1,
  },
  {
    id: "p34",
    title: "Most expensive product",
    level: 3,
    difficulty: 2,
    topics: ["MAX"],
    goal: "Use MAX.",
    problem: "Return the highest price across all products.",
    starter_sql: "SELECT MAX(price) FROM products;",
    solution: "SELECT MAX(price) FROM products;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["MAX(price)"],
    explanation: "MAX returns the largest value in a column.",
    estimated_time_min: 1,
  },
  {
    id: "p35",
    title: "Products per category",
    level: 3,
    difficulty: 2,
    topics: ["GROUP BY", "COUNT"],
    goal: "Group + count.",
    problem: "Return each category and the number of products in it.",
    starter_sql: "SELECT category, COUNT(*) AS n FROM products GROUP BY category;",
    solution: "SELECT category, COUNT(*) AS n FROM products GROUP BY category;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["GROUP BY category"],
    explanation: "GROUP BY collapses rows by the grouping key.",
    estimated_time_min: 2,
  },
  {
    id: "p36",
    title: "Average price per category",
    level: 3,
    difficulty: 2,
    topics: ["GROUP BY", "AVG"],
    goal: "Group + average.",
    problem: "Return each category with the average product price in that category.",
    starter_sql: "SELECT category, AVG(price) FROM products GROUP BY category;",
    solution: "SELECT category, AVG(price) FROM products GROUP BY category;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["AVG(price) per group"],
    explanation: "Aggregates run independently per group.",
    estimated_time_min: 2,
  },
  {
    id: "p37",
    title: "Categories with > 2 products",
    level: 3,
    difficulty: 3,
    topics: ["GROUP BY", "HAVING"],
    goal: "Filter aggregated results.",
    problem: "Return categories that contain more than 2 products.",
    starter_sql: "SELECT category, COUNT(*) AS n FROM products GROUP BY category HAVING ;",
    solution: "SELECT category, COUNT(*) AS n FROM products GROUP BY category HAVING COUNT(*) > 2;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["HAVING filters AFTER aggregation"],
    explanation: "WHERE filters rows; HAVING filters groups.",
    estimated_time_min: 3,
  },
  {
    id: "p38",
    title: "Orders per status",
    level: 3,
    difficulty: 2,
    topics: ["GROUP BY", "COUNT"],
    goal: "Count per status.",
    problem: "Return each order status and how many orders have that status.",
    starter_sql: "SELECT status, COUNT(*) FROM orders GROUP BY status;",
    solution: "SELECT status, COUNT(*) FROM orders GROUP BY status;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["GROUP BY status"],
    explanation: "Classic categorical breakdown.",
    estimated_time_min: 2,
  },
  {
    id: "p39",
    title: "Total spent per user",
    level: 3,
    difficulty: 3,
    topics: ["JOIN", "GROUP BY", "SUM"],
    goal: "Aggregate across joined tables.",
    problem: "Return user name and the total amount they have paid (sum of payments where status='paid'). Users with no paid payments should be excluded.",
    starter_sql: "SELECT u.name, SUM(p.amount) AS total FROM users u JOIN orders o ON o.user_id = u.id JOIN payments p ON p.order_id = o.id WHERE p.status = 'paid' GROUP BY u.name;",
    solution: "SELECT u.name, SUM(p.amount) AS total FROM users u JOIN orders o ON o.user_id = u.id JOIN payments p ON p.order_id = o.id WHERE p.status = 'paid' GROUP BY u.name;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["JOIN through orders to payments", "filter then group"],
    explanation: "Combine joins, WHERE, and GROUP BY for revenue per customer.",
    estimated_time_min: 4,
  },
  {
    id: "p40",
    title: "Average order size",
    level: 3,
    difficulty: 3,
    topics: ["GROUP BY", "AVG", "subquery"],
    goal: "Aggregate of aggregates.",
    problem: "Return the average number of items per order (avg of total quantity per order).",
    starter_sql: "SELECT AVG(total_qty) FROM (SELECT order_id, SUM(quantity) AS total_qty FROM order_items GROUP BY order_id);",
    solution: "SELECT AVG(total_qty) FROM (SELECT order_id, SUM(quantity) AS total_qty FROM order_items GROUP BY order_id);",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["Subquery first, then AVG"],
    explanation: "Aggregating an aggregated subquery is a common pattern.",
    estimated_time_min: 4,
  },

  // ============= LEVEL 4 — SUBQUERIES (7) =============
  {
    id: "p41",
    title: "Users who ordered",
    level: 4,
    difficulty: 2,
    topics: ["IN", "subquery"],
    goal: "Use IN with a subquery.",
    problem: "Return users who have placed at least one order.",
    starter_sql: "SELECT * FROM users WHERE id IN (SELECT  FROM orders);",
    solution: "SELECT * FROM users WHERE id IN (SELECT user_id FROM orders);",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["IN (subquery returning user_id)"],
    explanation: "IN against a subquery is one way to express membership.",
    estimated_time_min: 3,
  },
  {
    id: "p42",
    title: "Products never ordered (subquery)",
    level: 4,
    difficulty: 3,
    topics: ["NOT IN", "subquery"],
    goal: "NOT IN with a subquery.",
    problem: "Return products whose id never appears in `order_items.product_id`.",
    starter_sql: "SELECT * FROM products WHERE id NOT IN (SELECT product_id FROM order_items);",
    solution: "SELECT * FROM products WHERE id NOT IN (SELECT product_id FROM order_items);",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["NOT IN", "Beware NULLs in real data"],
    explanation: "NOT IN is concise but can misbehave with NULLs in the subquery.",
    estimated_time_min: 3,
  },
  {
    id: "p43",
    title: "Above-average price",
    level: 4,
    difficulty: 3,
    topics: ["subquery", "AVG"],
    goal: "Compare to a scalar subquery.",
    problem: "Return products whose price is greater than the average product price.",
    starter_sql: "SELECT * FROM products WHERE price > (SELECT AVG(price) FROM products);",
    solution: "SELECT * FROM products WHERE price > (SELECT AVG(price) FROM products);",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["The subquery returns one number"],
    explanation: "Scalar subqueries plug into expressions like a literal.",
    estimated_time_min: 3,
  },
  {
    id: "p44",
    title: "EXISTS: users with payments",
    level: 4,
    difficulty: 3,
    topics: ["EXISTS", "correlated subquery"],
    goal: "Use a correlated EXISTS.",
    problem: "Return users who have at least one payment (any status). Use EXISTS.",
    starter_sql: "SELECT * FROM users u WHERE EXISTS (SELECT 1 FROM orders o JOIN payments p ON p.order_id = o.id WHERE o.user_id = u.id);",
    solution: "SELECT * FROM users u WHERE EXISTS (SELECT 1 FROM orders o JOIN payments p ON p.order_id = o.id WHERE o.user_id = u.id);",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["EXISTS (...) checks if the inner query returns any row"],
    explanation: "EXISTS is often clearer than IN for existence checks.",
    estimated_time_min: 4,
  },
  {
    id: "p45",
    title: "Most expensive product per category",
    level: 4,
    difficulty: 4,
    topics: ["correlated subquery", "MAX"],
    goal: "Per-group max via correlated subquery.",
    problem: "Return products whose price equals the maximum price in their own category.",
    starter_sql: "SELECT * FROM products p WHERE price = (SELECT MAX(price) FROM products WHERE category = p.category);",
    solution: "SELECT * FROM products p WHERE price = (SELECT MAX(price) FROM products WHERE category = p.category);",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["Correlate the inner query on category"],
    explanation: "Correlated subqueries reference the outer row.",
    estimated_time_min: 5,
  },
  {
    id: "p46",
    title: "Users with no completed orders",
    level: 4,
    difficulty: 3,
    topics: ["NOT EXISTS"],
    goal: "Negative existence check.",
    problem: "Return users who have NOT placed any order with status='completed'.",
    starter_sql: "SELECT * FROM users u WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.user_id = u.id AND o.status = 'completed');",
    solution: "SELECT * FROM users u WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.user_id = u.id AND o.status = 'completed');",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["NOT EXISTS for safe anti-join"],
    explanation: "NOT EXISTS is the NULL-safe alternative to NOT IN.",
    estimated_time_min: 4,
  },
  {
    id: "p47",
    title: "Categories with average above 200",
    level: 4,
    difficulty: 4,
    topics: ["subquery", "GROUP BY"],
    goal: "Subquery with grouping.",
    problem: "Return category names whose average product price is greater than 200.",
    starter_sql: "SELECT category FROM products GROUP BY category HAVING AVG(price) > 200;",
    solution: "SELECT category FROM products GROUP BY category HAVING AVG(price) > 200;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["HAVING AVG(price) > 200"],
    explanation: "HAVING with an aggregate is the cleanest form here.",
    estimated_time_min: 3,
  },

  // ============= LEVEL 5 — ADVANCED (3) =============
  {
    id: "p48",
    title: "Top spending user",
    level: 5,
    difficulty: 4,
    topics: ["JOIN", "GROUP BY", "ORDER BY", "LIMIT"],
    goal: "Combine multiple concepts.",
    problem: "Return the single user (name, total) who has paid the most across paid payments.",
    starter_sql: "SELECT u.name, SUM(p.amount) AS total FROM users u JOIN orders o ON u.id = o.user_id JOIN payments p ON o.id = p.order_id WHERE p.status='paid' GROUP BY u.name ORDER BY total DESC LIMIT 1;",
    solution: "SELECT u.name, SUM(p.amount) AS total FROM users u JOIN orders o ON u.id = o.user_id JOIN payments p ON o.id = p.order_id WHERE p.status='paid' GROUP BY u.name ORDER BY total DESC LIMIT 1;",
    validation: { ignore_order: false, ignore_column_names: true },
    hints: ["JOIN, filter, group, order desc, limit 1"],
    explanation: "Top-N aggregation: filter, group, order, limit.",
    estimated_time_min: 5,
  },
  {
    id: "p49",
    title: "Repeat customers",
    level: 5,
    difficulty: 3,
    topics: ["GROUP BY", "HAVING"],
    goal: "Find users meeting an aggregate threshold.",
    problem: "Return user_ids of users who have placed more than one order.",
    starter_sql: "SELECT user_id FROM orders GROUP BY user_id HAVING COUNT(*) > 1;",
    solution: "SELECT user_id FROM orders GROUP BY user_id HAVING COUNT(*) > 1;",
    validation: { ignore_order: true, ignore_column_names: true },
    hints: ["GROUP BY user_id", "HAVING COUNT(*) > 1"],
    explanation: "HAVING filters groups by their aggregate value.",
    estimated_time_min: 3,
  },
  {
    id: "p50",
    title: "Best-selling product",
    level: 5,
    difficulty: 4,
    topics: ["JOIN", "GROUP BY", "ORDER BY", "LIMIT"],
    goal: "Rank products by sold quantity.",
    problem: "Return the product (name, total_sold) with the highest total quantity sold across all orders.",
    starter_sql: "SELECT p.name, SUM(oi.quantity) AS total_sold FROM products p JOIN order_items oi ON oi.product_id = p.id GROUP BY p.name ORDER BY total_sold DESC LIMIT 1;",
    solution: "SELECT p.name, SUM(oi.quantity) AS total_sold FROM products p JOIN order_items oi ON oi.product_id = p.id GROUP BY p.name ORDER BY total_sold DESC LIMIT 1;",
    validation: { ignore_order: false, ignore_column_names: true },
    hints: ["JOIN, SUM(quantity), order desc, limit 1"],
    explanation: "Same Top-N pattern, applied to product sales.",
    estimated_time_min: 5,
  },
];

export function getProblem(id: string): Problem | undefined {
  return PROBLEMS.find((p) => p.id === id);
}
