/**
 * 150 atomiske ferdigheter dekkende DTE-bachelor i IT på HVL.
 *
 * Hver ferdighet har:
 *  - et menneskelig navn på norsk
 *  - direkte prereqs (transitive lukning beregnes i graph.ts)
 *  - evidens som peker på FAKTISKE oppgaver/innhold i denne kodebasen
 *
 * Sorter i sub-grupper for lesbarhet; rekkefølge er IKKE topologisk —
 * graph.ts validerer at det ikke finnes sykluser og kan sortere topologisk
 * når engine trenger det.
 */

import type { FagOmrade, Skill } from "./types";

/**
 * Fag-områder brukt av diagnose-test og recommender for å gruppere ferdigheter.
 * Hver `id` matcher FagOmrade i types.ts.
 */
export type SkillArea = { id: FagOmrade; navn: string };

export function getAreaTitle(id: FagOmrade): string {
  return SKILL_AREAS.find((a) => a.id === id)?.navn ?? id;
}

export const SKILL_AREAS: SkillArea[] = [
  { id: "math", navn: "Matematikk" },
  { id: "programming", navn: "Programmering" },
  { id: "data-structures", navn: "Data-strukturer & algoritmer" },
  { id: "os", navn: "Operativsystemer" },
  { id: "networks", navn: "Nettverk" },
  { id: "databases", navn: "Databaser" },
  { id: "web", navn: "Web-utvikling" },
  { id: "ml-classical", navn: "Klassisk ML" },
  { id: "ml-deep", navn: "Dyplæring" },
  { id: "security", navn: "Sikkerhet" },
  { id: "engineering-practice", navn: "Ingeniør-praksis" },
];

export const SKILLS: Skill[] = [
  // ────────────────────────────────────────────────────────────────────────
  // MATH FOUNDATIONS (12)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "math-variables",
    navn: "Variabler og uttrykk",
    blurb: "Symbolsk regning — bruke bokstaver for ukjente, manipulere uttrykk.",
    omrade: "math",
    bloom: "apply",
    prereqs: [],
    evidens: { stackSlugs: ["math-foundations"] },
    estimertTid: "30 min",
  },
  {
    id: "math-functions",
    navn: "Funksjoner",
    blurb: "Definisjonsmengde/verdimengde, sammensetning, invers — fundamentet for alt videre.",
    omrade: "math",
    bloom: "understand",
    prereqs: ["math-variables"],
    evidens: { stackSlugs: ["math-foundations"] },
    estimertTid: "1 t",
  },
  {
    id: "math-derivatives",
    navn: "Derivasjon",
    blurb: "Stigningstall, kjerneregel, anvendt på optimering og kostfunksjoner i ML.",
    omrade: "math",
    bloom: "apply",
    prereqs: ["math-functions"],
    evidens: { stackSlugs: ["math-foundations", "optimering"] },
    estimertTid: "2 t",
  },
  {
    id: "math-integrals",
    navn: "Integrasjon",
    blurb: "Areal under kurve, sannsynlighetstettheter, kumulative fordelinger.",
    omrade: "math",
    bloom: "apply",
    prereqs: ["math-derivatives"],
    evidens: { stackSlugs: ["math-foundations"] },
    estimertTid: "2 t",
  },
  {
    id: "math-vectors",
    navn: "Vektorer",
    blurb: "Lengde, skalarprodukt, projeksjon — geometrien bak ML-modeller.",
    omrade: "math",
    bloom: "apply",
    prereqs: ["math-variables"],
    evidens: { stackSlugs: ["linaer-algebra"] },
    estimertTid: "1 t",
  },
  {
    id: "math-matrices",
    navn: "Matriser og lineære avbildninger",
    blurb: "Matrise-vektor-produkt, identitet, invers, determinant.",
    omrade: "math",
    bloom: "apply",
    prereqs: ["math-vectors"],
    evidens: { stackSlugs: ["linaer-algebra"] },
    estimertTid: "2 t",
  },
  {
    id: "math-eigenvalues",
    navn: "Egenverdier og egenvektorer",
    blurb: "Diagonalisering, brukt i PCA og spektralmetoder.",
    omrade: "math",
    bloom: "analyze",
    prereqs: ["math-matrices", "math-derivatives"],
    evidens: { stackSlugs: ["linaer-algebra", "dte2501-pca"] },
    estimertTid: "2 t",
  },
  {
    id: "math-probability",
    navn: "Sannsynlighet — grunnlag",
    blurb: "Utfallsrom, hendelser, sannsynlighetsregning, kombinatorikk.",
    omrade: "math",
    bloom: "apply",
    prereqs: ["math-variables"],
    evidens: { stackSlugs: ["sannsynlighet", "tek1-sannsynlighet", "tek1-kombinatorikk"] },
    estimertTid: "2 t",
  },
  {
    id: "math-conditional-prob",
    navn: "Betinget sannsynlighet og Bayes",
    blurb: "P(A|B), uavhengighet, Bayes' teorem — fundamentet for probabilistisk ML.",
    omrade: "math",
    bloom: "apply",
    prereqs: ["math-probability"],
    evidens: { stackSlugs: ["bayes", "tek1-sannsynlighet"] },
    estimertTid: "1-2 t",
  },
  {
    id: "math-distributions",
    navn: "Sannsynlighetsfordelinger",
    blurb: "Binomisk, Poisson, normal, eksponentialfordeling — diskret og kontinuerlig.",
    omrade: "math",
    bloom: "apply",
    prereqs: ["math-conditional-prob", "math-integrals"],
    evidens: { stackSlugs: ["tek1-fordelinger", "tek1-diskrete-fordelinger", "tek1-kontinuerlige-fordelinger", "tek1-distribusjons-plotter"] },
    estimertTid: "2-3 t",
  },
  {
    id: "math-descriptive-stats",
    navn: "Deskriptiv statistikk",
    blurb: "Forventning, varians, standardavvik, kvartiler — beskrive datasett.",
    omrade: "math",
    bloom: "apply",
    prereqs: ["math-probability"],
    evidens: { stackSlugs: ["tek1-deskriptiv", "tek1-forventning-clt"] },
    estimertTid: "1-2 t",
  },
  {
    id: "math-hypothesis-test",
    navn: "Hypotesetesting og KI",
    blurb: "Konfidensintervall, p-verdi, type I/II-feil, t-test, proporsjonstest.",
    omrade: "math",
    bloom: "analyze",
    prereqs: ["math-distributions", "math-descriptive-stats"],
    evidens: { stackSlugs: ["tek1-estimering-ki", "tek1-hypotesetest-regresjon", "tek1-p-verdi-kalkulator", "tek1-proporsjoner", "tek1-anova", "tek1-statistisk-analyse"] },
    estimertTid: "3-4 t",
  },

  // ────────────────────────────────────────────────────────────────────────
  // PROGRAMMING GRUNNLAG (15)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "prog-variables",
    navn: "Variabler og tilordning",
    blurb: "Navngitte verdier, referanser vs. verdier i Python.",
    omrade: "programming",
    bloom: "apply",
    prereqs: [],
    evidens: { stackSlugs: ["python-drill"], flashcardIds: ["c-db"] },
    estimertTid: "20 min",
  },
  {
    id: "prog-types",
    navn: "Primitive datatyper",
    blurb: "int, float, str, bool — type-konvertering og operatorer.",
    omrade: "programming",
    bloom: "apply",
    prereqs: ["prog-variables"],
    evidens: { stackSlugs: ["python-drill", "typesystemer"] },
    estimertTid: "30 min",
  },
  {
    id: "prog-control-flow",
    navn: "Kontrollflyt",
    blurb: "if/elif/else, while, for, break, continue.",
    omrade: "programming",
    bloom: "apply",
    prereqs: ["prog-types"],
    evidens: { stackSlugs: ["python-drill"] },
    estimertTid: "1 t",
  },
  {
    id: "prog-functions",
    navn: "Funksjoner",
    blurb: "Definere, kalle, default-args, *args/**kwargs, return.",
    omrade: "programming",
    bloom: "apply",
    prereqs: ["prog-control-flow"],
    evidens: { stackSlugs: ["python-drill"] },
    estimertTid: "1 t",
  },
  {
    id: "prog-lists",
    navn: "Lister",
    blurb: "Indeksering, slicing, append/pop, list comprehension.",
    omrade: "programming",
    bloom: "apply",
    prereqs: ["prog-control-flow"],
    evidens: { stackSlugs: ["python-drill"] },
    estimertTid: "1 t",
  },
  {
    id: "prog-dicts-sets",
    navn: "Dictionaries og sets",
    blurb: "Nøkkel-verdi-oppslag, mengder, hashing under panseret.",
    omrade: "programming",
    bloom: "apply",
    prereqs: ["prog-lists"],
    evidens: { stackSlugs: ["python-drill", "hashing-dypere"] },
    estimertTid: "1 t",
  },
  {
    id: "prog-scope",
    navn: "Scope og navnerom",
    blurb: "LEGB-regel, global/nonlocal, closures.",
    omrade: "programming",
    bloom: "analyze",
    prereqs: ["prog-functions"],
    evidens: { stackSlugs: ["python-drill"] },
    estimertTid: "1 t",
  },
  {
    id: "prog-classes",
    navn: "Klasser og OO",
    blurb: "__init__, metoder, arv, polymorfi, dataclasses.",
    omrade: "programming",
    bloom: "apply",
    prereqs: ["prog-functions", "prog-dicts-sets"],
    evidens: { stackSlugs: ["python-drill", "funksjonell-programmering"] },
    estimertTid: "2 t",
  },
  {
    id: "prog-exceptions",
    navn: "Exception handling",
    blurb: "try/except/finally, raise, custom exceptions.",
    omrade: "programming",
    bloom: "apply",
    prereqs: ["prog-functions"],
    evidens: { stackSlugs: ["python-drill"] },
    estimertTid: "45 min",
  },
  {
    id: "prog-file-io",
    navn: "Fil-IO",
    blurb: "open(), context managers, lese/skrive tekst og JSON.",
    omrade: "programming",
    bloom: "apply",
    prereqs: ["prog-exceptions", "prog-lists"],
    evidens: { stackSlugs: ["python-drill"] },
    estimertTid: "1 t",
  },
  {
    id: "prog-decorators",
    navn: "Decorators",
    blurb: "@decorator, functools.wraps — wrappe funksjoner deklarativt.",
    omrade: "programming",
    bloom: "analyze",
    prereqs: ["prog-scope", "prog-classes"],
    evidens: {
      pyExerciseIds: [
        "py-functools-wraps-init",
        "py-flask-login-1-decorator",
        "py-flask-login-3-combine",
      ],
    },
    estimertTid: "1-2 t",
  },
  {
    id: "prog-generators",
    navn: "Generators og iteratorer",
    blurb: "yield, lazy evaluation, itertools.",
    omrade: "programming",
    bloom: "analyze",
    prereqs: ["prog-functions", "prog-lists"],
    evidens: { stackSlugs: ["funksjonell-programmering", "korutiner"] },
    estimertTid: "1 t",
  },
  {
    id: "prog-type-hints",
    navn: "Type hints",
    blurb: "PEP 484, typing-modul, mypy — gradvis typing i Python.",
    omrade: "programming",
    bloom: "apply",
    prereqs: ["prog-functions", "prog-classes"],
    evidens: { stackSlugs: ["typesystemer", "typescript"] },
    estimertTid: "1 t",
  },
  {
    id: "prog-modules",
    navn: "Moduler og pakker",
    blurb: "import, from, __init__.py, relative imports.",
    omrade: "programming",
    bloom: "apply",
    prereqs: ["prog-functions"],
    evidens: { stackSlugs: ["python-drill"] },
    estimertTid: "45 min",
  },
  {
    id: "prog-venv-pip",
    navn: "Virtual environments og pip",
    blurb: "Isolerte avhengigheter, requirements.txt, pyproject.toml.",
    omrade: "programming",
    bloom: "apply",
    prereqs: ["prog-modules"],
    evidens: { stackSlugs: ["python-drill"] },
    estimertTid: "30 min",
  },

  // ────────────────────────────────────────────────────────────────────────
  // DATASTRUKTURER + ALGORITMER (18)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "ds-arrays",
    navn: "Arrays",
    blurb: "Sammenhengende minneblokk, O(1) random access, dynamic arrays.",
    omrade: "data-structures",
    bloom: "understand",
    prereqs: ["prog-lists"],
    evidens: { stackSlugs: ["algoritmer", "lenkede-strukturer"] },
    estimertTid: "45 min",
  },
  {
    id: "ds-linked-lists",
    navn: "Lenkede lister",
    blurb: "Single/dobbel-lenket, head/tail, fordeler vs. arrays.",
    omrade: "data-structures",
    bloom: "apply",
    prereqs: ["prog-classes", "ds-arrays"],
    evidens: { stackSlugs: ["lenkede-strukturer"] },
    estimertTid: "1-2 t",
  },
  {
    id: "ds-stack",
    navn: "Stack (LIFO)",
    blurb: "push/pop, call stack, evaluering av uttrykk.",
    omrade: "data-structures",
    bloom: "apply",
    prereqs: ["ds-arrays"],
    evidens: { stackSlugs: ["algoritmer"] },
    estimertTid: "45 min",
  },
  {
    id: "ds-queue",
    navn: "Queue (FIFO)",
    blurb: "enqueue/dequeue, deque, brukt i BFS og scheduling.",
    omrade: "data-structures",
    bloom: "apply",
    prereqs: ["ds-linked-lists"],
    evidens: { stackSlugs: ["algoritmer"] },
    estimertTid: "45 min",
  },
  {
    id: "ds-hash-table",
    navn: "Hash-tabeller",
    blurb: "Hash-funksjon, kollisjonshåndtering, amortisert O(1).",
    omrade: "data-structures",
    bloom: "analyze",
    prereqs: ["prog-dicts-sets"],
    evidens: { stackSlugs: ["hashing-dypere"] },
    estimertTid: "2 t",
  },
  {
    id: "ds-trees",
    navn: "Trær",
    blurb: "Node/edge, rot/blad, traversering (pre/in/post-order).",
    omrade: "data-structures",
    bloom: "apply",
    prereqs: ["ds-linked-lists"],
    evidens: { stackSlugs: ["traer"] },
    estimertTid: "2 t",
  },
  {
    id: "ds-bst",
    navn: "Binære søketrær",
    blurb: "BST-invariant, insert/search/delete, balanseringsproblem.",
    omrade: "data-structures",
    bloom: "apply",
    prereqs: ["ds-trees"],
    evidens: { stackSlugs: ["traer"] },
    estimertTid: "2 t",
  },
  {
    id: "ds-heap",
    navn: "Heap / priority queue",
    blurb: "Min/max-heap, heapify, brukt i Dijkstra og scheduling.",
    omrade: "data-structures",
    bloom: "apply",
    prereqs: ["ds-trees", "ds-arrays"],
    evidens: { stackSlugs: ["traer", "sortering"] },
    estimertTid: "2 t",
  },
  {
    id: "ds-graphs",
    navn: "Grafer",
    blurb: "Vertex/edge, retta/uretta, adjacency-liste vs. matrise.",
    omrade: "data-structures",
    bloom: "apply",
    prereqs: ["ds-trees", "ds-hash-table"],
    evidens: { stackSlugs: ["grafer-dypere"] },
    estimertTid: "2 t",
  },
  {
    id: "algo-big-o",
    navn: "Big-O notasjon",
    blurb: "Tid- og plasskompleksitet, worst/best/average case.",
    omrade: "data-structures",
    bloom: "analyze",
    prereqs: ["prog-control-flow"],
    evidens: { stackSlugs: ["big-o"] },
    estimertTid: "1-2 t",
  },
  {
    id: "algo-amortized",
    navn: "Amortisert analyse",
    blurb: "Aggregert/bankkonto-metoden, dynamic array doubling.",
    omrade: "data-structures",
    bloom: "analyze",
    prereqs: ["algo-big-o"],
    evidens: { stackSlugs: ["big-o", "hashing-dypere"] },
    estimertTid: "1 t",
  },
  {
    id: "algo-recursion",
    navn: "Rekursjon",
    blurb: "Base case, rekursiv case, call stack, tail recursion.",
    omrade: "data-structures",
    bloom: "apply",
    prereqs: ["prog-functions", "prog-lists", "prog-scope"],
    evidens: { stackSlugs: ["rekursjon"] },
    estimertTid: "2 t",
  },
  {
    id: "algo-binary-search",
    navn: "Binærsøk",
    blurb: "O(log n) på sortert array, invariantbevis.",
    omrade: "data-structures",
    bloom: "apply",
    prereqs: ["ds-arrays", "algo-big-o", "algo-recursion"],
    evidens: { stackSlugs: ["sok-algoritmer", "algoritmer"] },
    estimertTid: "1 t",
  },
  {
    id: "algo-sorting",
    navn: "Sortering — sammenligningsbasert",
    blurb: "Quick, merge, heap sort. O(n log n) nedre grense.",
    omrade: "data-structures",
    bloom: "analyze",
    prereqs: ["algo-recursion", "ds-heap", "algo-big-o"],
    evidens: { stackSlugs: ["sortering"] },
    estimertTid: "3 t",
  },
  {
    id: "algo-bfs-dfs",
    navn: "BFS og DFS",
    blurb: "Graftraversering med kø vs. stack, visited-set.",
    omrade: "data-structures",
    bloom: "apply",
    prereqs: ["ds-graphs", "ds-queue", "ds-stack"],
    evidens: { stackSlugs: ["sok-algoritmer", "grafer-dypere"] },
    estimertTid: "2 t",
  },
  {
    id: "algo-dp",
    navn: "Dynamisk programmering",
    blurb: "Memoization, tabulering, overlappende delproblemer.",
    omrade: "data-structures",
    bloom: "analyze",
    prereqs: ["algo-recursion", "ds-arrays"],
    evidens: { stackSlugs: ["dynamic-programming", "dte2501-dp"], pyExerciseIds: ["py-dte2501-knapsack-dp"] },
    estimertTid: "3-4 t",
  },
  {
    id: "algo-greedy",
    navn: "Grådig algoritme",
    blurb: "Lokalt optimalt valg, matroide-intuisjon.",
    omrade: "data-structures",
    bloom: "analyze",
    prereqs: ["algo-big-o", "algo-sorting"],
    evidens: { stackSlugs: ["algoritmer"] },
    estimertTid: "2 t",
  },
  {
    id: "algo-divide-conquer",
    navn: "Splitt-og-hersk",
    blurb: "Mester-teoremet, anvendt på merge sort, FFT, Strassen.",
    omrade: "data-structures",
    bloom: "analyze",
    prereqs: ["algo-recursion", "algo-big-o"],
    evidens: { stackSlugs: ["algoritmer", "sortering"] },
    estimertTid: "2 t",
  },

  // ────────────────────────────────────────────────────────────────────────
  // OS (15)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "os-process",
    navn: "Prosess",
    blurb: "PCB, fork/exec, prosess-tilstander, /proc.",
    omrade: "os",
    bloom: "understand",
    prereqs: ["prog-modules"],
    evidens: {
      stackSlugs: ["os-grunnlag", "dte2505-prosesser-signaler"],
      pyExerciseIds: ["py-dte2505-ps-parse"],
    },
    estimertTid: "1-2 t",
  },
  {
    id: "os-thread",
    navn: "Tråder",
    blurb: "Konkurrens vs. parallelisme, race conditions, GIL.",
    omrade: "os",
    bloom: "analyze",
    prereqs: ["os-process"],
    evidens: { stackSlugs: ["dte2505-konkurrens", "korutiner"] },
    estimertTid: "2 t",
  },
  {
    id: "os-scheduling",
    navn: "CPU-scheduling",
    blurb: "FCFS, SJF, Round-Robin, multilevel feedback.",
    omrade: "os",
    bloom: "analyze",
    prereqs: ["os-process"],
    evidens: { stackSlugs: ["dte2505-scheduling-drill"] },
    estimertTid: "2 t",
  },
  {
    id: "os-virtual-memory",
    navn: "Virtuelt minne",
    blurb: "Adresseoversettelse, page faults, demand paging.",
    omrade: "os",
    bloom: "analyze",
    prereqs: ["os-process"],
    evidens: { stackSlugs: ["dte2505-virtuelt-minne", "trinn-6-c-minne"] },
    estimertTid: "2-3 t",
  },
  {
    id: "os-page-table",
    navn: "Page table",
    blurb: "Single/multi-level, virtuell → fysisk side, sidestørrelse.",
    omrade: "os",
    bloom: "analyze",
    prereqs: ["os-virtual-memory"],
    evidens: { stackSlugs: ["dte2505-virtuelt-minne"] },
    estimertTid: "1-2 t",
  },
  {
    id: "os-tlb",
    navn: "TLB",
    blurb: "Translation Lookaside Buffer, hit rate, lokalitet.",
    omrade: "os",
    bloom: "understand",
    prereqs: ["os-page-table"],
    evidens: { stackSlugs: ["dte2505-virtuelt-minne"] },
    estimertTid: "45 min",
  },
  {
    id: "os-filesystem",
    navn: "Filsystem",
    blurb: "inodes, directory tree, mounting, hard/symlinks.",
    omrade: "os",
    bloom: "understand",
    prereqs: ["os-process"],
    evidens: { stackSlugs: ["dte2505-filsystem"] },
    estimertTid: "1-2 t",
  },
  {
    id: "os-syscalls",
    navn: "Systemkall",
    blurb: "User/kernel mode, syscall-grensesnitt, strace.",
    omrade: "os",
    bloom: "understand",
    prereqs: ["os-process"],
    evidens: { stackSlugs: ["trinn-9-syscalls-dyp", "trinn-8-python-er-c"] },
    estimertTid: "2 t",
  },
  {
    id: "os-ipc-pipes",
    navn: "IPC og pipes",
    blurb: "Pipes, named pipes, message queues, shared memory.",
    omrade: "os",
    bloom: "apply",
    prereqs: ["os-syscalls"],
    evidens: { stackSlugs: ["dte2505-ipc"] },
    estimertTid: "1-2 t",
  },
  {
    id: "os-semaphores",
    navn: "Semaforer og låser",
    blurb: "Mutex, semafor, producer-consumer, monitors.",
    omrade: "os",
    bloom: "apply",
    prereqs: ["os-thread"],
    evidens: { stackSlugs: ["dte2505-konkurrens"] },
    estimertTid: "2 t",
  },
  {
    id: "os-deadlock",
    navn: "Deadlock",
    blurb: "Fire betingelser, deteksjon, prevention, Banker's algorithm.",
    omrade: "os",
    bloom: "analyze",
    prereqs: ["os-semaphores"],
    evidens: { stackSlugs: ["dte2505-konkurrens"] },
    estimertTid: "1-2 t",
  },
  {
    id: "os-signals",
    navn: "Signaler",
    blurb: "SIGINT, SIGKILL, signal handlers, kill(2).",
    omrade: "os",
    bloom: "apply",
    prereqs: ["os-process"],
    evidens: { stackSlugs: ["dte2505-prosesser-signaler"] },
    estimertTid: "1 t",
  },
  {
    id: "os-shell",
    navn: "Shell og bash-scripting",
    blurb: "Pipelines, redirection, jobs, scripting basics.",
    omrade: "os",
    bloom: "apply",
    prereqs: ["os-filesystem"],
    evidens: {
      stackSlugs: ["linux-bruk", "linux-cli-advanced", "shell-scripting", "dte2505-bash-scripts"],
      pyExerciseIds: ["py-dte2505-bash-output"],
    },
    estimertTid: "3-4 t",
  },
  {
    id: "os-permissions",
    navn: "Filrettigheter (rwx)",
    blurb: "chmod oktale verdier, eier/gruppe, setuid/setgid/sticky.",
    omrade: "os",
    bloom: "apply",
    prereqs: ["os-filesystem"],
    evidens: {
      stackSlugs: ["dte2505-rwx-kalkulator", "dte2505-spesialbits", "brukere-rettigheter"],
      pyExerciseIds: [
        "py-dte2505-passwd-parse",
        "py-dte2505-chmod-octal",
        "py-dte2505-pathlib-perms",
      ],
    },
    estimertTid: "1-2 t",
  },
  {
    id: "os-containers",
    navn: "Containere",
    blurb: "Namespaces, cgroups, Docker-isolasjon vs. VM.",
    omrade: "os",
    bloom: "understand",
    prereqs: ["os-process", "os-filesystem"],
    evidens: { stackSlugs: ["docker", "dockerfile-builder", "virtualisering", "dte2505-virtualisering"] },
    estimertTid: "2 t",
  },

  // ────────────────────────────────────────────────────────────────────────
  // NETWORKS (18)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "net-osi-tcpip",
    navn: "OSI og TCP/IP-modellen",
    blurb: "Lagene, encapsulation, ansvarsfordeling per lag.",
    omrade: "networks",
    bloom: "understand",
    prereqs: [],
    evidens: { stackSlugs: ["osi-tcpip"] },
    estimertTid: "1-2 t",
  },
  {
    id: "net-ip-subnetting",
    navn: "IP og subnetting",
    blurb: "IPv4-adresser, CIDR, subnet-mask, VLSM.",
    omrade: "networks",
    bloom: "apply",
    prereqs: ["net-osi-tcpip"],
    evidens: {
      stackSlugs: ["dte2507-subnetting"],
      pyExerciseIds: ["py-dte2507-subnet-calc"],
    },
    estimertTid: "2-3 t",
  },
  {
    id: "net-arp",
    navn: "ARP",
    blurb: "Mapping IP → MAC, ARP-cache, gratuitous ARP.",
    omrade: "networks",
    bloom: "understand",
    prereqs: ["net-ip-subnetting"],
    evidens: { stackSlugs: ["dte2507-arp-detektiv"] },
    estimertTid: "45 min",
  },
  {
    id: "net-dhcp",
    navn: "DHCP",
    blurb: "DORA-handshake, lease, relay-agent.",
    omrade: "networks",
    bloom: "understand",
    prereqs: ["net-ip-subnetting"],
    evidens: { stackSlugs: ["dte2507-dhcp"] },
    estimertTid: "45 min",
  },
  {
    id: "net-dns",
    navn: "DNS",
    blurb: "Hierarki, rekursiv vs. iterativ, cache, A/AAAA/MX/CNAME.",
    omrade: "networks",
    bloom: "understand",
    prereqs: ["net-ip-subnetting"],
    evidens: { stackSlugs: ["dte2507-dns-dyp"] },
    estimertTid: "1-2 t",
  },
  {
    id: "net-tcp-handshake",
    navn: "TCP three-way handshake",
    blurb: "SYN/SYN-ACK/ACK, sekvensnummer, FIN/RST.",
    omrade: "networks",
    bloom: "analyze",
    prereqs: ["net-osi-tcpip"],
    evidens: { stackSlugs: ["transportlag", "tcp-sockets"] },
    estimertTid: "1-2 t",
  },
  {
    id: "net-congestion-control",
    navn: "TCP congestion control",
    blurb: "Slow start, AIMD, fast retransmit, CUBIC vs. Reno.",
    omrade: "networks",
    bloom: "analyze",
    prereqs: ["net-tcp-handshake"],
    evidens: { stackSlugs: ["dte2507-congestion-control", "dte2507-bottleneck-throughput"] },
    estimertTid: "2 t",
  },
  {
    id: "net-rdt-progression",
    navn: "Reliable Data Transfer-progresjonen",
    blurb: "rdt 1.0 → 3.0, stop-and-wait → pipelined, GBN/SR.",
    omrade: "networks",
    bloom: "analyze",
    prereqs: ["net-tcp-handshake"],
    evidens: { stackSlugs: ["dte2507-rdt-progresjon", "dte2507-ap-progresjon"] },
    estimertTid: "2-3 t",
  },
  {
    id: "net-http",
    navn: "HTTP/1, HTTP/2 og HTTP/3",
    blurb: "Forskjeller på multiplexing, HoL-blocking, QUIC.",
    omrade: "networks",
    bloom: "understand",
    prereqs: ["net-tcp-handshake"],
    evidens: {
      stackSlugs: ["http-anatomi", "dte2507-http2-hol", "dte2507-web-caching-matte"],
      pyExerciseIds: ["py-dte2507-http-parse"],
    },
    estimertTid: "2 t",
  },
  {
    id: "net-tls",
    navn: "TLS",
    blurb: "TLS 1.3 handshake, sertifikater, perfect forward secrecy.",
    omrade: "networks",
    bloom: "analyze",
    prereqs: ["net-http", "sec-crypto-basics"],
    evidens: {
      stackSlugs: ["tls", "dte2507-tls-handshake"],
      pyExerciseIds: ["py-dte2507-cert-parse"],
    },
    estimertTid: "2-3 t",
  },
  {
    id: "net-bgp",
    navn: "BGP",
    blurb: "Path-vector, AS-stier, policy-based routing, hijacks.",
    omrade: "networks",
    bloom: "understand",
    prereqs: ["net-ip-subnetting"],
    evidens: { stackSlugs: ["dte2507-bgp-stige"] },
    estimertTid: "1-2 t",
  },
  {
    id: "net-ospf",
    navn: "OSPF og link-state",
    blurb: "Dijkstra på nett, areas, LSA-typer; count-to-infinity-problem i DV.",
    omrade: "networks",
    bloom: "analyze",
    prereqs: ["net-ip-subnetting", "algo-bfs-dfs"],
    evidens: { stackSlugs: ["dte2507-ruting", "dte2507-count-to-infinity"] },
    estimertTid: "2-3 t",
  },
  {
    id: "net-nat",
    navn: "NAT",
    blurb: "PAT/SNAT/DNAT, port-mapping, hairpinning.",
    omrade: "networks",
    bloom: "understand",
    prereqs: ["net-ip-subnetting"],
    evidens: { stackSlugs: ["dte2507-nat"] },
    estimertTid: "1 t",
  },
  {
    id: "net-sockets",
    navn: "Socket-programmering",
    blurb: "BSD sockets, TCP/UDP server, blocking vs. non-blocking.",
    omrade: "networks",
    bloom: "apply",
    prereqs: ["net-tcp-handshake", "prog-file-io"],
    evidens: {
      stackSlugs: ["tcp-sockets", "dte2507-socket-programmering"],
      pyExerciseIds: ["py-dte2507-socket-skeleton"],
    },
    estimertTid: "2-3 t",
  },
  {
    id: "sec-crypto-basics",
    navn: "Kryptografi — grunnlag",
    blurb: "Symmetrisk vs. asymmetrisk, hash, MAC, IV/nonce.",
    omrade: "networks",
    bloom: "understand",
    prereqs: ["math-conditional-prob"],
    evidens: {
      stackSlugs: ["kryptografi", "dte2507-cbc-iv", "dte2507-fra-checksum-til-hmac"],
      pyExerciseIds: ["py-dte2507-caesar-vigenere", "py-dte2507-hashlib", "py-dte2507-hmac"],
    },
    estimertTid: "2-3 t",
  },
  {
    id: "sec-rsa-dh",
    navn: "RSA og Diffie-Hellman",
    blurb: "Modulær aritmetikk, nøkkelutveksling, signering.",
    omrade: "networks",
    bloom: "apply",
    prereqs: ["sec-crypto-basics", "math-conditional-prob"],
    evidens: {
      stackSlugs: ["dte2507-rsa-mini"],
      pyExerciseIds: ["py-dte2507-rsa-mini"],
    },
    estimertTid: "2 t",
  },
  {
    id: "sec-hmac",
    navn: "HMAC og message authentication",
    blurb: "Keyed hash for integritet + autentisering, timing attacks.",
    omrade: "networks",
    bloom: "apply",
    prereqs: ["sec-crypto-basics"],
    evidens: {
      stackSlugs: ["dte2507-fra-checksum-til-hmac"],
      pyExerciseIds: ["py-dte2507-hmac"],
    },
    estimertTid: "1 t",
  },
  {
    id: "sec-ids-firewall",
    navn: "IDS og brannmur",
    blurb: "Stateful/stateless, Snort-regler, IDS vs. IPS.",
    omrade: "networks",
    bloom: "understand",
    prereqs: ["net-tcp-handshake"],
    evidens: {
      stackSlugs: [
        "dte2507-ids-snort",
        "dte2507-brannmur-vlan",
        "dte2507-stateful-firewall",
        "nettverkssikkerhet",
      ],
    },
    estimertTid: "2 t",
  },

  // ────────────────────────────────────────────────────────────────────────
  // DATABASER (12)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "db-er-model",
    navn: "ER-modellering",
    blurb: "Entiteter, attributter, relasjoner, kardinaliteter.",
    omrade: "databases",
    bloom: "apply",
    prereqs: [],
    evidens: {
      stackSlugs: ["er-mapping"],
      flashcardIds: ["c-relasjon", "c-mn", "c-kard"],
    },
    estimertTid: "2 t",
  },
  {
    id: "db-keys",
    navn: "Nøkler (PK/FK)",
    blurb: "Primær- og fremmednøkler, sammensatte nøkler, surrogatnøkler.",
    omrade: "databases",
    bloom: "apply",
    prereqs: ["db-er-model"],
    evidens: {
      stackSlugs: ["nokler"],
      flashcardIds: ["c-pk", "c-fk", "c-pk-vs-fk"],
    },
    estimertTid: "1 t",
  },
  {
    id: "db-normalization",
    navn: "Normalisering (1-3NF)",
    blurb: "Funksjonelle avhengigheter, BCNF, denormalisering når ytelse krever.",
    omrade: "databases",
    bloom: "analyze",
    prereqs: ["db-keys"],
    evidens: { stackSlugs: ["normalisering"] },
    estimertTid: "2-3 t",
  },
  {
    id: "db-select",
    navn: "SELECT, WHERE, ORDER BY",
    blurb: "Grunnleggende spørringer mot én tabell.",
    omrade: "databases",
    bloom: "apply",
    prereqs: [],
    evidens: {
      sqlProblemIds: ["p1", "p2", "p3", "p4", "p5"],
      flashcardIds: ["c-db", "c-tabell", "c-rad", "c-kolonne"],
    },
    estimertTid: "1-2 t",
  },
  {
    id: "db-joins",
    navn: "JOIN-typer",
    blurb: "INNER, LEFT/RIGHT/FULL OUTER, CROSS, SELF.",
    omrade: "databases",
    bloom: "apply",
    prereqs: ["db-select", "db-keys"],
    evidens: {
      sqlProblemIds: ["p10", "p11", "p12"],
      dragExerciseIds: ["d-match-joins"],
    },
    estimertTid: "2-3 t",
  },
  {
    id: "db-group-having",
    navn: "GROUP BY og HAVING",
    blurb: "Aggregater (COUNT/SUM/AVG), filtrering på grupper.",
    omrade: "databases",
    bloom: "apply",
    prereqs: ["db-select"],
    evidens: { sqlProblemIds: ["p15", "p16", "p17"] },
    estimertTid: "1-2 t",
  },
  {
    id: "db-subqueries",
    navn: "Subqueries og CTEs",
    blurb: "Korrelerte subqueries, EXISTS, WITH-klausul.",
    omrade: "databases",
    bloom: "analyze",
    prereqs: ["db-joins", "db-group-having"],
    evidens: { stackSlugs: ["subqueries"], sqlProblemIds: ["p20", "p21"] },
    estimertTid: "2-3 t",
  },
  {
    id: "db-window-functions",
    navn: "Vindusfunksjoner",
    blurb: "ROW_NUMBER, RANK, LAG/LEAD, OVER(PARTITION BY).",
    omrade: "databases",
    bloom: "analyze",
    prereqs: ["db-subqueries"],
    evidens: { sqlProblemIds: ["p30", "p31"] },
    estimertTid: "2-3 t",
  },
  {
    id: "db-indexes",
    navn: "Indekser",
    blurb: "B-tree, hash, dekkende indeks, cost vs. benefit.",
    omrade: "databases",
    bloom: "analyze",
    prereqs: ["db-joins", "ds-bst"],
    evidens: { stackSlugs: ["indekser", "query-optimisering"] },
    estimertTid: "2 t",
  },
  {
    id: "db-transactions",
    navn: "Transaksjoner og ACID",
    blurb: "BEGIN/COMMIT/ROLLBACK, isolation levels, locking.",
    omrade: "databases",
    bloom: "analyze",
    prereqs: ["db-select"],
    evidens: {
      stackSlugs: ["transaksjoner"],
      dragExerciseIds: ["d-match-acid", "d-order-transaction"],
      flashcardIds: ["c-pk"],
    },
    estimertTid: "2-3 t",
  },
  {
    id: "db-query-plan",
    navn: "Query plan og EXPLAIN",
    blurb: "Tabell-scan vs. indeks-scan, hash join vs. nested loop.",
    omrade: "databases",
    bloom: "evaluate",
    prereqs: ["db-indexes"],
    evidens: { stackSlugs: ["query-optimisering"] },
    estimertTid: "2 t",
  },
  {
    id: "db-mysql-pg-sqlite",
    navn: "MySQL vs. Postgres vs. SQLite",
    blurb: "Forskjeller i typer, dialekt og transaksjonsstøtte mellom de tre vanligste DBMS-ene.",
    omrade: "databases",
    bloom: "understand",
    prereqs: ["db-select", "db-transactions"],
    evidens: { stackSlugs: ["mysql-vs-sqlite"] },
    estimertTid: "1 t",
  },
  {
    id: "db-nosql-mindset",
    navn: "NoSQL-tankegang",
    blurb: "Dokument-, kolonne- og nøkkel/verdi-databaser; CAP-teoremet, eventual consistency.",
    omrade: "databases",
    bloom: "understand",
    prereqs: ["db-mysql-pg-sqlite"],
    evidens: { stackSlugs: ["mysql-vs-sqlite"] },
    estimertTid: "1-2 t",
  },

  // ────────────────────────────────────────────────────────────────────────
  // WEB / FULL-STACK (12)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "web-http-anatomy",
    navn: "HTTP-anatomi",
    blurb: "Metoder, statuskoder, headers, cookies.",
    omrade: "web",
    bloom: "understand",
    prereqs: ["net-http"],
    evidens: { stackSlugs: ["http-anatomi"] },
    estimertTid: "1-2 t",
  },
  {
    id: "web-html",
    navn: "HTML",
    blurb: "Semantiske tags, skjemaer, accessibility-grunnlag.",
    omrade: "web",
    bloom: "apply",
    prereqs: [],
    evidens: { stackSlugs: ["html-jinja"] },
    estimertTid: "2-3 t",
  },
  {
    id: "web-css",
    navn: "CSS — flexbox og grid",
    blurb: "Box-model, layout med flex/grid, responsive design.",
    omrade: "web",
    bloom: "apply",
    prereqs: ["web-html"],
    evidens: { stackSlugs: ["css-moderne"] },
    estimertTid: "3-4 t",
  },
  {
    id: "web-js-basics",
    navn: "JavaScript — grunnlag",
    blurb: "Variabler, funksjoner, closures, DOM-manipulasjon.",
    omrade: "web",
    bloom: "apply",
    prereqs: ["prog-control-flow"],
    evidens: { stackSlugs: ["javascript-grunnlag"] },
    estimertTid: "3-4 t",
  },
  {
    id: "web-typescript",
    navn: "TypeScript",
    blurb: "Type-system, interfaces, generics, strict mode.",
    omrade: "web",
    bloom: "apply",
    prereqs: ["web-js-basics", "prog-type-hints"],
    evidens: { stackSlugs: ["typescript", "typesystemer"] },
    estimertTid: "2-3 t",
  },
  {
    id: "web-react-components",
    navn: "React — komponenter",
    blurb: "JSX, props, komponent-sammensetning.",
    omrade: "web",
    bloom: "apply",
    prereqs: ["web-typescript"],
    evidens: { stackSlugs: ["react-grunnlag"] },
    estimertTid: "2-3 t",
  },
  {
    id: "web-react-state",
    navn: "React — state",
    blurb: "useState, prop drilling, lifting state up.",
    omrade: "web",
    bloom: "apply",
    prereqs: ["web-react-components"],
    evidens: { stackSlugs: ["react-grunnlag"] },
    estimertTid: "2 t",
  },
  {
    id: "web-react-hooks",
    navn: "React — hooks",
    blurb: "useEffect, useMemo, useCallback, custom hooks.",
    omrade: "web",
    bloom: "analyze",
    prereqs: ["web-react-state"],
    evidens: { stackSlugs: ["react-grunnlag"] },
    estimertTid: "2-3 t",
  },
  {
    id: "web-flask-routes",
    navn: "Flask / FastAPI routes",
    blurb: "Route-decorators, URL-parametre, request/response.",
    omrade: "web",
    bloom: "apply",
    prereqs: ["prog-decorators", "web-http-anatomy"],
    evidens: {
      stackSlugs: ["flask-livssyklus", "flask-app-builder", "fastapi-grunnlag", "fastapi-app-builder"],
      pyExerciseIds: ["py-flask-route-init", "py-flask-hello", "py-flask-url-param", "py-flask-multi-param"],
    },
    estimertTid: "2-3 t",
  },
  {
    id: "web-jinja-templates",
    navn: "Jinja-templates",
    blurb: "Variabler, kontrollflyt, escaping, template-arv.",
    omrade: "web",
    bloom: "apply",
    prereqs: ["web-flask-routes", "web-html"],
    evidens: {
      stackSlugs: ["html-jinja"],
      pyExerciseIds: ["py-flask-jinja"],
    },
    estimertTid: "1-2 t",
  },
  {
    id: "web-sessions",
    navn: "Sessions og autentisering",
    blurb: "Cookies, server-side sessions, login-decorator.",
    omrade: "web",
    bloom: "analyze",
    prereqs: ["web-flask-routes", "sec-passwords"],
    evidens: {
      pyExerciseIds: [
        "py-flask-secret-key-init",
        "py-flask-session-init",
        "py-flask-session",
        "py-flask-login-2-post-login",
        "py-flask-login-4-full-test",
      ],
    },
    estimertTid: "2-3 t",
  },
  {
    id: "web-rest-api",
    navn: "REST-API-design",
    blurb: "Ressurser, HTTP-verb, statuskoder, versjonering, idempotens.",
    omrade: "web",
    bloom: "analyze",
    prereqs: ["web-flask-routes"],
    evidens: {
      stackSlugs: ["api-arkitektur", "api-kontrakt", "api-planlegging", "rest-api-builder"],
      pyExerciseIds: ["py-flask-json-api"],
    },
    estimertTid: "2-3 t",
  },

  // ────────────────────────────────────────────────────────────────────────
  // ML KLASSISK (15)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "ml-knn",
    navn: "k-NN",
    blurb: "Lazy learner, distansemål, kurset for høy dimensjon.",
    omrade: "ml-classical",
    bloom: "apply",
    prereqs: ["math-vectors", "prog-classes"],
    evidens: {
      stackSlugs: ["dte2501-knn"],
      pyExerciseIds: ["py-dte2501-knn-iris", "py-dte2501-knn-regression"],
    },
    estimertTid: "2 t",
  },
  {
    id: "ml-kmeans",
    navn: "k-Means",
    blurb: "Iterativt centroid-update, elbow, sårbar for init.",
    omrade: "ml-classical",
    bloom: "apply",
    prereqs: ["math-vectors", "algo-big-o"],
    evidens: {
      stackSlugs: ["dte2501-kmeans-clustering", "dte2501-kmeans-visualizer"],
      pyExerciseIds: ["py-dte2501-kmeans-blobs", "py-dte2501-kmeans-manual"],
    },
    estimertTid: "2-3 t",
  },
  {
    id: "ml-gmm",
    navn: "GMM og EM",
    blurb: "Gaussian Mixture Model, Expectation-Maximization, BIC-valg.",
    omrade: "ml-classical",
    bloom: "analyze",
    prereqs: ["ml-kmeans", "math-distributions"],
    evidens: {
      stackSlugs: ["dte2501-gmm"],
      pyExerciseIds: ["py-dte2501-gmm-2d", "py-dte2501-gmm-bic-search"],
    },
    estimertTid: "3 t",
  },
  {
    id: "ml-pca",
    navn: "PCA",
    blurb: "Dimensjonsreduksjon via SVD / egenvektorer av kovariansmatrise.",
    omrade: "ml-classical",
    bloom: "analyze",
    prereqs: ["math-eigenvalues", "math-descriptive-stats"],
    evidens: {
      stackSlugs: ["dte2501-pca", "dte2501-pca-visualizer"],
      pyExerciseIds: ["py-dte2501-pca-iris", "py-dte2501-pca-manual"],
    },
    estimertTid: "2-3 t",
  },
  {
    id: "ml-decision-tree",
    navn: "Decision tree",
    blurb: "Gini/entropy, splits, overfitting, pruning.",
    omrade: "ml-classical",
    bloom: "apply",
    prereqs: ["math-conditional-prob"],
    evidens: {
      stackSlugs: ["dte2602-trees-rf"],
      pyExerciseIds: ["py-dte2501-tree-iris", "py-dte2501-tree-gini"],
    },
    estimertTid: "2-3 t",
  },
  {
    id: "ml-random-forest",
    navn: "Random Forest og bagging",
    blurb: "Bootstrap, feature bagging, OOB-score.",
    omrade: "ml-classical",
    bloom: "analyze",
    prereqs: ["ml-decision-tree"],
    evidens: {
      stackSlugs: ["dte2602-trees-rf"],
      pyExerciseIds: ["py-dte2501-rf-gbm"],
    },
    estimertTid: "2 t",
  },
  {
    id: "ml-naive-bayes",
    navn: "Naive Bayes",
    blurb: "Bayes' regel med uavhengighetsantakelse, Gaussian/Multinomial NB.",
    omrade: "ml-classical",
    bloom: "apply",
    prereqs: ["math-conditional-prob"],
    evidens: { stackSlugs: ["bayes", "dte2602-lda-qda-nb"] },
    estimertTid: "1-2 t",
  },
  {
    id: "ml-logistic-regression",
    navn: "Logistisk regresjon",
    blurb: "Sigmoid, log-loss, gradient descent for klassifisering.",
    omrade: "ml-classical",
    bloom: "analyze",
    prereqs: ["math-derivatives", "math-vectors"],
    evidens: { stackSlugs: ["dte2602-logistisk-regresjon"] },
    estimertTid: "2-3 t",
  },
  {
    id: "ml-svm",
    navn: "SVM",
    blurb: "Maksimal margin, kernel trick, soft margin.",
    omrade: "ml-classical",
    bloom: "analyze",
    prereqs: ["math-vectors", "math-derivatives"],
    evidens: { stackSlugs: ["dte2602-svm"] },
    estimertTid: "3 t",
  },
  {
    id: "ml-ensemble",
    navn: "Ensemble-metoder",
    blurb: "Boosting (AdaBoost, GBM), stacking, blending.",
    omrade: "ml-classical",
    bloom: "analyze",
    prereqs: ["ml-random-forest"],
    evidens: {
      stackSlugs: ["dte2501-ensemble"],
      pyExerciseIds: ["py-dte2501-adaboost-weights", "py-dte2501-rf-gbm"],
    },
    estimertTid: "2-3 t",
  },
  {
    id: "ml-genetic-algos",
    navn: "Genetiske algoritmer",
    blurb: "Populasjon, crossover, mutasjon, fitness.",
    omrade: "ml-classical",
    bloom: "apply",
    prereqs: ["algo-recursion"],
    evidens: {
      stackSlugs: ["dte2501-genetic-algorithms", "dte2501-pso-visualizer"],
      pyExerciseIds: ["py-dte2501-ga-onemax"],
    },
    estimertTid: "2 t",
  },
  {
    id: "ml-nlp-basics",
    navn: "NLP — grunnlag",
    blurb: "Tokenisering, TF-IDF, cosine similarity, n-grammer.",
    omrade: "ml-classical",
    bloom: "apply",
    prereqs: ["math-vectors", "prog-dicts-sets"],
    evidens: {
      stackSlugs: ["dte2501-nlp-intro"],
      pyExerciseIds: ["py-dte2501-tfidf-cosine", "py-dte2501-tfidf-search"],
    },
    estimertTid: "2-3 t",
  },
  {
    id: "ml-bandits",
    navn: "Multi-armed bandits",
    blurb: "Exploration vs. exploitation, ε-greedy, UCB.",
    omrade: "ml-classical",
    bloom: "analyze",
    prereqs: ["math-probability"],
    evidens: { stackSlugs: ["dte2501-bandits"] },
    estimertTid: "2 t",
  },
  {
    id: "ml-mdp-bellman",
    navn: "MDP og Bellman",
    blurb: "States, actions, rewards, value iteration, Q-learning.",
    omrade: "ml-classical",
    bloom: "analyze",
    prereqs: ["math-conditional-prob", "ml-bandits"],
    evidens: {
      stackSlugs: ["dte2501-mdp-bellman", "dte2501-reinforcement"],
      pyExerciseIds: ["py-dte2501-vi-grid", "py-dte2501-qlearn"],
    },
    estimertTid: "3-4 t",
  },
  {
    id: "ml-a-star",
    navn: "A*-søk og heuristikker",
    blurb: "f = g + h, admissibility, consistency.",
    omrade: "ml-classical",
    bloom: "analyze",
    prereqs: ["algo-bfs-dfs", "ds-heap"],
    evidens: { stackSlugs: ["sok-algoritmer", "dte2501-minimax"] },
    estimertTid: "2 t",
  },

  // ────────────────────────────────────────────────────────────────────────
  // ML DYP (10)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "dl-perceptron",
    navn: "Perceptron",
    blurb: "Lineær klassifikator, oppdateringsregel, XOR-problemet.",
    omrade: "ml-deep",
    bloom: "apply",
    prereqs: ["math-vectors", "ml-logistic-regression"],
    evidens: { stackSlugs: ["nn-intro"] },
    estimertTid: "1-2 t",
  },
  {
    id: "dl-backprop",
    navn: "Backpropagation",
    blurb: "Kjerneregelen gjennom flerlags-nett, chain rule i praksis.",
    omrade: "ml-deep",
    bloom: "analyze",
    prereqs: ["dl-perceptron", "math-derivatives"],
    evidens: { stackSlugs: ["backprop-dyp"] },
    estimertTid: "3-4 t",
  },
  {
    id: "dl-optimization",
    navn: "Optimering — SGD og Adam",
    blurb: "Mini-batch, momentum, learning rate schedules.",
    omrade: "ml-deep",
    bloom: "analyze",
    prereqs: ["dl-backprop"],
    evidens: { stackSlugs: ["optimering"] },
    estimertTid: "2 t",
  },
  {
    id: "dl-regularization",
    navn: "Regularisering",
    blurb: "L1/L2, weight decay, early stopping.",
    omrade: "ml-deep",
    bloom: "analyze",
    prereqs: ["dl-backprop"],
    evidens: { stackSlugs: ["regularisering"] },
    estimertTid: "1-2 t",
  },
  {
    id: "dl-dropout",
    navn: "Dropout",
    blurb: "Stokastisk maskering ved trening, implisitt ensemble.",
    omrade: "ml-deep",
    bloom: "apply",
    prereqs: ["dl-regularization"],
    evidens: { stackSlugs: ["regularisering"] },
    estimertTid: "30 min",
  },
  {
    id: "dl-batch-norm",
    navn: "Batch normalization",
    blurb: "Normalisering per mini-batch, akselererer trening.",
    omrade: "ml-deep",
    bloom: "analyze",
    prereqs: ["dl-optimization"],
    evidens: { stackSlugs: ["regularisering"] },
    estimertTid: "1 t",
  },
  {
    id: "dl-cnn",
    navn: "CNN",
    blurb: "Konvolusjon, pooling, parameterdeling for bildedata.",
    omrade: "ml-deep",
    bloom: "analyze",
    prereqs: ["dl-backprop"],
    evidens: { stackSlugs: ["cnn"] },
    estimertTid: "3-4 t",
  },
  {
    id: "dl-rnn",
    navn: "RNN og LSTM",
    blurb: "Sekvensmodeller, BPTT, vanishing gradients.",
    omrade: "ml-deep",
    bloom: "analyze",
    prereqs: ["dl-backprop"],
    evidens: { stackSlugs: ["pytorch-tf"] },
    estimertTid: "3 t",
  },
  {
    id: "dl-transfer-learning",
    navn: "Transfer learning",
    blurb: "Pre-trained backbone, fine-tuning, feature extraction.",
    omrade: "ml-deep",
    bloom: "apply",
    prereqs: ["dl-cnn"],
    evidens: { stackSlugs: ["pytorch-tf"] },
    estimertTid: "2 t",
  },
  {
    id: "dl-attention",
    navn: "Attention og transformere",
    blurb: "Query/key/value, self-attention, positional encoding.",
    omrade: "ml-deep",
    bloom: "analyze",
    prereqs: ["dl-rnn", "math-matrices"],
    evidens: { stackSlugs: ["pytorch-tf"] },
    estimertTid: "4 t",
  },

  // ────────────────────────────────────────────────────────────────────────
  // SIKKERHET (8) — sec-crypto-basics, sec-rsa-dh, sec-hmac, sec-ids-firewall ligger over
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "sec-threat-modeling",
    navn: "Trusselmodellering",
    blurb: "STRIDE, angrepsoverflate, asset-første tankegang.",
    omrade: "security",
    bloom: "analyze",
    prereqs: [],
    evidens: { stackSlugs: ["sikkerhet"] },
    estimertTid: "1-2 t",
  },
  {
    id: "sec-csrf",
    navn: "CSRF",
    blurb: "Cross-site request forgery, SameSite cookies, CSRF-tokens.",
    omrade: "security",
    bloom: "analyze",
    prereqs: ["web-sessions"],
    evidens: { stackSlugs: ["sikkerhet"], dragExerciseIds: ["d-match-security"] },
    estimertTid: "1 t",
  },
  {
    id: "sec-xss",
    navn: "XSS",
    blurb: "Stored/reflected/DOM, Content-Security-Policy, escaping.",
    omrade: "security",
    bloom: "analyze",
    prereqs: ["web-jinja-templates"],
    evidens: { stackSlugs: ["sikkerhet"], dragExerciseIds: ["d-match-security"] },
    estimertTid: "1-2 t",
  },
  {
    id: "sec-sqli",
    navn: "SQL-injection",
    blurb: "Parametriserte queries, prepared statements, escape vs. bind.",
    omrade: "security",
    bloom: "analyze",
    prereqs: ["db-select"],
    evidens: {
      pyExerciseIds: ["py-db-injection-bad", "py-db-prepared"],
      dragExerciseIds: ["d-match-security"],
    },
    estimertTid: "1-2 t",
  },
  {
    id: "sec-passwords",
    navn: "Passordlagring",
    blurb: "Hashing + salt + cost (bcrypt/argon2), aldri plaintext.",
    omrade: "security",
    bloom: "analyze",
    prereqs: ["sec-crypto-basics"],
    evidens: {
      pyExerciseIds: [
        "py-pwd-1-plaintext-problem",
        "py-pwd-hash-init",
        "py-pwd-2-werkzeug-hash",
      ],
    },
    estimertTid: "1-2 t",
  },
  {
    id: "sec-oauth",
    navn: "OAuth 2.0 og OIDC",
    blurb: "Authorization code-flyt, scopes, bearer tokens, PKCE.",
    omrade: "security",
    bloom: "understand",
    prereqs: ["web-sessions", "net-tls"],
    evidens: { stackSlugs: ["sikkerhet"] },
    estimertTid: "2 t",
  },
  {
    id: "sec-least-privilege",
    navn: "Principle of least privilege",
    blurb: "Minst mulig tilgang for å gjøre jobben, separasjon av roller.",
    omrade: "security",
    bloom: "understand",
    prereqs: ["os-permissions"],
    evidens: { stackSlugs: ["sikkerhet", "brukere-rettigheter"] },
    estimertTid: "45 min",
  },

  // ────────────────────────────────────────────────────────────────────────
  // ENGINEERING PRACTICE (15)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "eng-git-basics",
    navn: "Git — grunnlag",
    blurb: "add, commit, push, pull, status, log.",
    omrade: "engineering-practice",
    bloom: "apply",
    prereqs: [],
    evidens: { stackSlugs: ["git-dyp"] },
    estimertTid: "1-2 t",
  },
  {
    id: "eng-git-branches",
    navn: "Git — branches og merge",
    blurb: "feature branches, merge vs. rebase, konflikthåndtering.",
    omrade: "engineering-practice",
    bloom: "apply",
    prereqs: ["eng-git-basics"],
    evidens: { stackSlugs: ["git-dyp"] },
    estimertTid: "2-3 t",
  },
  {
    id: "eng-refactoring",
    navn: "Refactoring",
    blurb: "Rename, extract method, inline, små trygge steg.",
    omrade: "engineering-practice",
    bloom: "evaluate",
    prereqs: ["prog-functions", "prog-classes"],
    evidens: { stackSlugs: ["funksjonell-programmering"] },
    estimertTid: "2 t",
  },
  {
    id: "eng-unit-testing",
    navn: "Unit-testing",
    blurb: "pytest/unittest, AAA-mønster, fixtures.",
    omrade: "engineering-practice",
    bloom: "apply",
    prereqs: ["prog-functions"],
    evidens: { stackSlugs: ["api-testing"] },
    estimertTid: "2-3 t",
  },
  {
    id: "eng-integration-testing",
    navn: "Integrasjons- og e2e-testing",
    blurb: "Test-pyramide, Flask test client, Playwright/Selenium.",
    omrade: "engineering-practice",
    bloom: "apply",
    prereqs: ["eng-unit-testing", "web-flask-routes"],
    evidens: {
      stackSlugs: ["api-testing"],
      pyExerciseIds: ["py-flask-test-client-init"],
    },
    estimertTid: "2-3 t",
  },
  {
    id: "eng-ci-cd",
    navn: "CI/CD",
    blurb: "GitHub Actions, pipelines, gates, automatisk deploy.",
    omrade: "engineering-practice",
    bloom: "apply",
    prereqs: ["eng-git-branches", "eng-unit-testing"],
    evidens: { stackSlugs: ["api-deploy"] },
    estimertTid: "2-3 t",
  },
  {
    id: "eng-docker",
    navn: "Docker",
    blurb: "Dockerfile, images, containere, volumes.",
    omrade: "engineering-practice",
    bloom: "apply",
    prereqs: ["os-containers"],
    evidens: { stackSlugs: ["docker", "dockerfile-builder"] },
    estimertTid: "2-3 t",
  },
  {
    id: "eng-code-review",
    navn: "Code review",
    blurb: "Konstruktiv tilbakemelding, små PR-er, sjekklister.",
    omrade: "engineering-practice",
    bloom: "evaluate",
    prereqs: ["eng-git-branches"],
    evidens: { stackSlugs: ["su-metodikker"] },
    estimertTid: "1-2 t",
  },
  {
    id: "eng-debugging",
    navn: "Debugging",
    blurb: "Print/breakpoint, debugger, binary search på commits.",
    omrade: "engineering-practice",
    bloom: "analyze",
    prereqs: ["prog-control-flow"],
    evidens: { stackSlugs: ["python-drill"] },
    estimertTid: "1-2 t",
  },
  {
    id: "eng-logging",
    navn: "Logging og observabilitet",
    blurb: "Strukturert logg-nivåer, korrelasjons-ID-er, distributed tracing.",
    omrade: "engineering-practice",
    bloom: "apply",
    prereqs: ["prog-modules"],
    evidens: { stackSlugs: ["api-deploy"] },
    estimertTid: "1-2 t",
  },
  {
    id: "eng-perf-profiling",
    navn: "Ytelses-profiling",
    blurb: "cProfile, flamegraph, finne flaskehalser.",
    omrade: "engineering-practice",
    bloom: "analyze",
    prereqs: ["algo-big-o", "eng-debugging"],
    evidens: { stackSlugs: ["query-optimisering"] },
    estimertTid: "2 t",
  },
  {
    id: "eng-technical-writing",
    navn: "Teknisk skriving",
    blurb: "README, ADR, docstrings, målgruppe-bevissthet.",
    omrade: "engineering-practice",
    bloom: "create",
    prereqs: ["prog-modules"],
    evidens: { stackSlugs: ["brukerhistorier", "planlegging"] },
    estimertTid: "1-2 t",
  },
  {
    id: "eng-system-design",
    navn: "Systemdesign — basics",
    blurb: "Lag, caching, load balancing, database sharding.",
    omrade: "engineering-practice",
    bloom: "evaluate",
    prereqs: ["web-rest-api", "db-indexes"],
    evidens: { stackSlugs: ["api-arkitektur", "api-planlegging"] },
    estimertTid: "3-4 t",
  },
  {
    id: "eng-agile-scrum",
    navn: "Agile og Scrum",
    blurb: "Sprint, backlog, retro, brukerhistorier.",
    omrade: "engineering-practice",
    bloom: "understand",
    prereqs: [],
    evidens: { stackSlugs: ["su-metodikker", "brukerhistorier", "su-prosjekt-praksis"] },
    estimertTid: "1-2 t",
  },
  {
    id: "eng-dry-solid",
    navn: "DRY og SOLID",
    blurb: "Don't Repeat Yourself, SRP/OCP/LSP/ISP/DIP.",
    omrade: "engineering-practice",
    bloom: "evaluate",
    prereqs: ["prog-classes", "eng-refactoring"],
    evidens: { stackSlugs: ["funksjonell-programmering"] },
    estimertTid: "2 t",
  },
];

/** Hurtigoppslag: id → Skill */
export const SKILL_BY_ID: Map<string, Skill> = new Map(SKILLS.map((s) => [s.id, s]));
