/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PythonRouteImport } from './routes/python'
import { Route as ProsjektRouteImport } from './routes/prosjekt'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as KursRouteImport } from './routes/kurs'
import { Route as KonsollRouteImport } from './routes/konsoll'
import { Route as JoinsRouteImport } from './routes/joins'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as ErTegnerRouteImport } from './routes/er-tegner'
import { Route as DragRouteImport } from './routes/drag'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as IndexRouteImport } from './routes/index'

const PythonRoute = PythonRouteImport.update({
  id: '/python',
  path: '/python',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsjektRoute = ProsjektRouteImport.update({
  id: '/prosjekt',
  path: '/prosjekt',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const KursRoute = KursRouteImport.update({
  id: '/kurs',
  path: '/kurs',
  getParentRoute: () => rootRouteImport,
} as any)
const KonsollRoute = KonsollRouteImport.update({
  id: '/konsoll',
  path: '/konsoll',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinsRoute = JoinsRouteImport.update({
  id: '/joins',
  path: '/joins',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const ErTegnerRoute = ErTegnerRouteImport.update({
  id: '/er-tegner',
  path: '/er-tegner',
  getParentRoute: () => rootRouteImport,
} as any)
const DragRoute = DragRouteImport.update({
  id: '/drag',
  path: '/drag',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/drag': typeof DragRoute
  '/er-tegner': typeof ErTegnerRoute
  '/exam': typeof ExamRoute
  '/joins': typeof JoinsRoute
  '/konsoll': typeof KonsollRoute
  '/kurs': typeof KursRoute
  '/learn': typeof LearnRoute
  '/practice': typeof PracticeRoute
  '/prosjekt': typeof ProsjektRoute
  '/python': typeof PythonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/drag': typeof DragRoute
  '/er-tegner': typeof ErTegnerRoute
  '/exam': typeof ExamRoute
  '/joins': typeof JoinsRoute
  '/konsoll': typeof KonsollRoute
  '/kurs': typeof KursRoute
  '/learn': typeof LearnRoute
  '/practice': typeof PracticeRoute
  '/prosjekt': typeof ProsjektRoute
  '/python': typeof PythonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/drag': typeof DragRoute
  '/er-tegner': typeof ErTegnerRoute
  '/exam': typeof ExamRoute
  '/joins': typeof JoinsRoute
  '/konsoll': typeof KonsollRoute
  '/kurs': typeof KursRoute
  '/learn': typeof LearnRoute
  '/practice': typeof PracticeRoute
  '/prosjekt': typeof ProsjektRoute
  '/python': typeof PythonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cards'
    | '/dashboard'
    | '/drag'
    | '/er-tegner'
    | '/exam'
    | '/joins'
    | '/konsoll'
    | '/kurs'
    | '/learn'
    | '/practice'
    | '/prosjekt'
    | '/python'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cards'
    | '/dashboard'
    | '/drag'
    | '/er-tegner'
    | '/exam'
    | '/joins'
    | '/konsoll'
    | '/kurs'
    | '/learn'
    | '/practice'
    | '/prosjekt'
    | '/python'
  id:
    | '__root__'
    | '/'
    | '/cards'
    | '/dashboard'
    | '/drag'
    | '/er-tegner'
    | '/exam'
    | '/joins'
    | '/konsoll'
    | '/kurs'
    | '/learn'
    | '/practice'
    | '/prosjekt'
    | '/python'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsRoute: typeof CardsRoute
  DashboardRoute: typeof DashboardRoute
  DragRoute: typeof DragRoute
  ErTegnerRoute: typeof ErTegnerRoute
  ExamRoute: typeof ExamRoute
  JoinsRoute: typeof JoinsRoute
  KonsollRoute: typeof KonsollRoute
  KursRoute: typeof KursRoute
  LearnRoute: typeof LearnRoute
  PracticeRoute: typeof PracticeRoute
  ProsjektRoute: typeof ProsjektRoute
  PythonRoute: typeof PythonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/python': {
      id: '/python'
      path: '/python'
      fullPath: '/python'
      preLoaderRoute: typeof PythonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prosjekt': {
      id: '/prosjekt'
      path: '/prosjekt'
      fullPath: '/prosjekt'
      preLoaderRoute: typeof ProsjektRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurs': {
      id: '/kurs'
      path: '/kurs'
      fullPath: '/kurs'
      preLoaderRoute: typeof KursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konsoll': {
      id: '/konsoll'
      path: '/konsoll'
      fullPath: '/konsoll'
      preLoaderRoute: typeof KonsollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joins': {
      id: '/joins'
      path: '/joins'
      fullPath: '/joins'
      preLoaderRoute: typeof JoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/er-tegner': {
      id: '/er-tegner'
      path: '/er-tegner'
      fullPath: '/er-tegner'
      preLoaderRoute: typeof ErTegnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drag': {
      id: '/drag'
      path: '/drag'
      fullPath: '/drag'
      preLoaderRoute: typeof DragRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsRoute: CardsRoute,
  DashboardRoute: DashboardRoute,
  DragRoute: DragRoute,
  ErTegnerRoute: ErTegnerRoute,
  ExamRoute: ExamRoute,
  JoinsRoute: JoinsRoute,
  KonsollRoute: KonsollRoute,
  KursRoute: KursRoute,
  LearnRoute: LearnRoute,
  PracticeRoute: PracticeRoute,
  ProsjektRoute: ProsjektRoute,
  PythonRoute: PythonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
