/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StackRouteImport } from './routes/stack'
import { Route as PythonRouteImport } from './routes/python'
import { Route as ProsjektRouteImport } from './routes/prosjekt'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as OvRouteImport } from './routes/ov'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LarRouteImport } from './routes/lar'
import { Route as KursRouteImport } from './routes/kurs'
import { Route as KonsollRouteImport } from './routes/konsoll'
import { Route as JoinsRouteImport } from './routes/joins'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as ErTegnerRouteImport } from './routes/er-tegner'
import { Route as EksamenRouteImport } from './routes/eksamen'
import { Route as DragRouteImport } from './routes/drag'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StackIndexRouteImport } from './routes/stack.index'
import { Route as StackSlugRouteImport } from './routes/stack.$slug'
import { Route as PythonVisualizerRouteImport } from './routes/python_.visualizer'
import { Route as ProsjektMlSlugRouteImport } from './routes/prosjekt-ml.$slug'
import { Route as PortfolioDte2602SlugRouteImport } from './routes/portfolio-dte2602.$slug'
import { Route as Dte2505ShellDrillRouteImport } from './routes/dte2505.shell-drill'
import { Route as PythonKapIndexRouteImport } from './routes/python_.kap.index'
import { Route as PythonKapNrRouteImport } from './routes/python_.kap.$nr'

const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonRoute = PythonRouteImport.update({
  id: '/python',
  path: '/python',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsjektRoute = ProsjektRouteImport.update({
  id: '/prosjekt',
  path: '/prosjekt',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const OvRoute = OvRouteImport.update({
  id: '/ov',
  path: '/ov',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LarRoute = LarRouteImport.update({
  id: '/lar',
  path: '/lar',
  getParentRoute: () => rootRouteImport,
} as any)
const KursRoute = KursRouteImport.update({
  id: '/kurs',
  path: '/kurs',
  getParentRoute: () => rootRouteImport,
} as any)
const KonsollRoute = KonsollRouteImport.update({
  id: '/konsoll',
  path: '/konsoll',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinsRoute = JoinsRouteImport.update({
  id: '/joins',
  path: '/joins',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const ErTegnerRoute = ErTegnerRouteImport.update({
  id: '/er-tegner',
  path: '/er-tegner',
  getParentRoute: () => rootRouteImport,
} as any)
const EksamenRoute = EksamenRouteImport.update({
  id: '/eksamen',
  path: '/eksamen',
  getParentRoute: () => rootRouteImport,
} as any)
const DragRoute = DragRouteImport.update({
  id: '/drag',
  path: '/drag',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StackIndexRoute = StackIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StackRoute,
} as any)
const StackSlugRoute = StackSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StackRoute,
} as any)
const PythonVisualizerRoute = PythonVisualizerRouteImport.update({
  id: '/python_/visualizer',
  path: '/python/visualizer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsjektMlSlugRoute = ProsjektMlSlugRouteImport.update({
  id: '/prosjekt-ml/$slug',
  path: '/prosjekt-ml/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioDte2602SlugRoute = PortfolioDte2602SlugRouteImport.update({
  id: '/portfolio-dte2602/$slug',
  path: '/portfolio-dte2602/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Dte2505ShellDrillRoute = Dte2505ShellDrillRouteImport.update({
  id: '/dte2505/shell-drill',
  path: '/dte2505/shell-drill',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonKapIndexRoute = PythonKapIndexRouteImport.update({
  id: '/python_/kap/',
  path: '/python/kap/',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonKapNrRoute = PythonKapNrRouteImport.update({
  id: '/python_/kap/$nr',
  path: '/python/kap/$nr',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/drag': typeof DragRoute
  '/eksamen': typeof EksamenRoute
  '/er-tegner': typeof ErTegnerRoute
  '/exam': typeof ExamRoute
  '/joins': typeof JoinsRoute
  '/konsoll': typeof KonsollRoute
  '/kurs': typeof KursRoute
  '/lar': typeof LarRoute
  '/learn': typeof LearnRoute
  '/ov': typeof OvRoute
  '/practice': typeof PracticeRoute
  '/prosjekt': typeof ProsjektRoute
  '/python': typeof PythonRoute
  '/stack': typeof StackRouteWithChildren
  '/dte2505/shell-drill': typeof Dte2505ShellDrillRoute
  '/portfolio-dte2602/$slug': typeof PortfolioDte2602SlugRoute
  '/prosjekt-ml/$slug': typeof ProsjektMlSlugRoute
  '/python/visualizer': typeof PythonVisualizerRoute
  '/stack/$slug': typeof StackSlugRoute
  '/stack/': typeof StackIndexRoute
  '/python/kap/$nr': typeof PythonKapNrRoute
  '/python/kap/': typeof PythonKapIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/drag': typeof DragRoute
  '/eksamen': typeof EksamenRoute
  '/er-tegner': typeof ErTegnerRoute
  '/exam': typeof ExamRoute
  '/joins': typeof JoinsRoute
  '/konsoll': typeof KonsollRoute
  '/kurs': typeof KursRoute
  '/lar': typeof LarRoute
  '/learn': typeof LearnRoute
  '/ov': typeof OvRoute
  '/practice': typeof PracticeRoute
  '/prosjekt': typeof ProsjektRoute
  '/python': typeof PythonRoute
  '/dte2505/shell-drill': typeof Dte2505ShellDrillRoute
  '/portfolio-dte2602/$slug': typeof PortfolioDte2602SlugRoute
  '/prosjekt-ml/$slug': typeof ProsjektMlSlugRoute
  '/python/visualizer': typeof PythonVisualizerRoute
  '/stack/$slug': typeof StackSlugRoute
  '/stack': typeof StackIndexRoute
  '/python/kap/$nr': typeof PythonKapNrRoute
  '/python/kap': typeof PythonKapIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/drag': typeof DragRoute
  '/eksamen': typeof EksamenRoute
  '/er-tegner': typeof ErTegnerRoute
  '/exam': typeof ExamRoute
  '/joins': typeof JoinsRoute
  '/konsoll': typeof KonsollRoute
  '/kurs': typeof KursRoute
  '/lar': typeof LarRoute
  '/learn': typeof LearnRoute
  '/ov': typeof OvRoute
  '/practice': typeof PracticeRoute
  '/prosjekt': typeof ProsjektRoute
  '/python': typeof PythonRoute
  '/stack': typeof StackRouteWithChildren
  '/dte2505/shell-drill': typeof Dte2505ShellDrillRoute
  '/portfolio-dte2602/$slug': typeof PortfolioDte2602SlugRoute
  '/prosjekt-ml/$slug': typeof ProsjektMlSlugRoute
  '/python_/visualizer': typeof PythonVisualizerRoute
  '/stack/$slug': typeof StackSlugRoute
  '/stack/': typeof StackIndexRoute
  '/python_/kap/$nr': typeof PythonKapNrRoute
  '/python_/kap/': typeof PythonKapIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cards'
    | '/dashboard'
    | '/drag'
    | '/eksamen'
    | '/er-tegner'
    | '/exam'
    | '/joins'
    | '/konsoll'
    | '/kurs'
    | '/lar'
    | '/learn'
    | '/ov'
    | '/practice'
    | '/prosjekt'
    | '/python'
    | '/stack'
    | '/dte2505/shell-drill'
    | '/portfolio-dte2602/$slug'
    | '/prosjekt-ml/$slug'
    | '/python/visualizer'
    | '/stack/$slug'
    | '/stack/'
    | '/python/kap/$nr'
    | '/python/kap/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cards'
    | '/dashboard'
    | '/drag'
    | '/eksamen'
    | '/er-tegner'
    | '/exam'
    | '/joins'
    | '/konsoll'
    | '/kurs'
    | '/lar'
    | '/learn'
    | '/ov'
    | '/practice'
    | '/prosjekt'
    | '/python'
    | '/dte2505/shell-drill'
    | '/portfolio-dte2602/$slug'
    | '/prosjekt-ml/$slug'
    | '/python/visualizer'
    | '/stack/$slug'
    | '/stack'
    | '/python/kap/$nr'
    | '/python/kap'
  id:
    | '__root__'
    | '/'
    | '/cards'
    | '/dashboard'
    | '/drag'
    | '/eksamen'
    | '/er-tegner'
    | '/exam'
    | '/joins'
    | '/konsoll'
    | '/kurs'
    | '/lar'
    | '/learn'
    | '/ov'
    | '/practice'
    | '/prosjekt'
    | '/python'
    | '/stack'
    | '/dte2505/shell-drill'
    | '/portfolio-dte2602/$slug'
    | '/prosjekt-ml/$slug'
    | '/python_/visualizer'
    | '/stack/$slug'
    | '/stack/'
    | '/python_/kap/$nr'
    | '/python_/kap/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsRoute: typeof CardsRoute
  DashboardRoute: typeof DashboardRoute
  DragRoute: typeof DragRoute
  EksamenRoute: typeof EksamenRoute
  ErTegnerRoute: typeof ErTegnerRoute
  ExamRoute: typeof ExamRoute
  JoinsRoute: typeof JoinsRoute
  KonsollRoute: typeof KonsollRoute
  KursRoute: typeof KursRoute
  LarRoute: typeof LarRoute
  LearnRoute: typeof LearnRoute
  OvRoute: typeof OvRoute
  PracticeRoute: typeof PracticeRoute
  ProsjektRoute: typeof ProsjektRoute
  PythonRoute: typeof PythonRoute
  StackRoute: typeof StackRouteWithChildren
  Dte2505ShellDrillRoute: typeof Dte2505ShellDrillRoute
  PortfolioDte2602SlugRoute: typeof PortfolioDte2602SlugRoute
  ProsjektMlSlugRoute: typeof ProsjektMlSlugRoute
  PythonVisualizerRoute: typeof PythonVisualizerRoute
  PythonKapNrRoute: typeof PythonKapNrRoute
  PythonKapIndexRoute: typeof PythonKapIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python': {
      id: '/python'
      path: '/python'
      fullPath: '/python'
      preLoaderRoute: typeof PythonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prosjekt': {
      id: '/prosjekt'
      path: '/prosjekt'
      fullPath: '/prosjekt'
      preLoaderRoute: typeof ProsjektRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ov': {
      id: '/ov'
      path: '/ov'
      fullPath: '/ov'
      preLoaderRoute: typeof OvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lar': {
      id: '/lar'
      path: '/lar'
      fullPath: '/lar'
      preLoaderRoute: typeof LarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurs': {
      id: '/kurs'
      path: '/kurs'
      fullPath: '/kurs'
      preLoaderRoute: typeof KursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konsoll': {
      id: '/konsoll'
      path: '/konsoll'
      fullPath: '/konsoll'
      preLoaderRoute: typeof KonsollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joins': {
      id: '/joins'
      path: '/joins'
      fullPath: '/joins'
      preLoaderRoute: typeof JoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/er-tegner': {
      id: '/er-tegner'
      path: '/er-tegner'
      fullPath: '/er-tegner'
      preLoaderRoute: typeof ErTegnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eksamen': {
      id: '/eksamen'
      path: '/eksamen'
      fullPath: '/eksamen'
      preLoaderRoute: typeof EksamenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drag': {
      id: '/drag'
      path: '/drag'
      fullPath: '/drag'
      preLoaderRoute: typeof DragRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack/': {
      id: '/stack/'
      path: '/'
      fullPath: '/stack/'
      preLoaderRoute: typeof StackIndexRouteImport
      parentRoute: typeof StackRoute
    }
    '/stack/$slug': {
      id: '/stack/$slug'
      path: '/$slug'
      fullPath: '/stack/$slug'
      preLoaderRoute: typeof StackSlugRouteImport
      parentRoute: typeof StackRoute
    }
    '/python_/visualizer': {
      id: '/python_/visualizer'
      path: '/python/visualizer'
      fullPath: '/python/visualizer'
      preLoaderRoute: typeof PythonVisualizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prosjekt-ml/$slug': {
      id: '/prosjekt-ml/$slug'
      path: '/prosjekt-ml/$slug'
      fullPath: '/prosjekt-ml/$slug'
      preLoaderRoute: typeof ProsjektMlSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-dte2602/$slug': {
      id: '/portfolio-dte2602/$slug'
      path: '/portfolio-dte2602/$slug'
      fullPath: '/portfolio-dte2602/$slug'
      preLoaderRoute: typeof PortfolioDte2602SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dte2505/shell-drill': {
      id: '/dte2505/shell-drill'
      path: '/dte2505/shell-drill'
      fullPath: '/dte2505/shell-drill'
      preLoaderRoute: typeof Dte2505ShellDrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python_/kap/': {
      id: '/python_/kap/'
      path: '/python/kap'
      fullPath: '/python/kap/'
      preLoaderRoute: typeof PythonKapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python_/kap/$nr': {
      id: '/python_/kap/$nr'
      path: '/python/kap/$nr'
      fullPath: '/python/kap/$nr'
      preLoaderRoute: typeof PythonKapNrRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StackRouteChildren {
  StackSlugRoute: typeof StackSlugRoute
  StackIndexRoute: typeof StackIndexRoute
}

const StackRouteChildren: StackRouteChildren = {
  StackSlugRoute: StackSlugRoute,
  StackIndexRoute: StackIndexRoute,
}

const StackRouteWithChildren = StackRoute._addFileChildren(StackRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsRoute: CardsRoute,
  DashboardRoute: DashboardRoute,
  DragRoute: DragRoute,
  EksamenRoute: EksamenRoute,
  ErTegnerRoute: ErTegnerRoute,
  ExamRoute: ExamRoute,
  JoinsRoute: JoinsRoute,
  KonsollRoute: KonsollRoute,
  KursRoute: KursRoute,
  LarRoute: LarRoute,
  LearnRoute: LearnRoute,
  OvRoute: OvRoute,
  PracticeRoute: PracticeRoute,
  ProsjektRoute: ProsjektRoute,
  PythonRoute: PythonRoute,
  StackRoute: StackRouteWithChildren,
  Dte2505ShellDrillRoute: Dte2505ShellDrillRoute,
  PortfolioDte2602SlugRoute: PortfolioDte2602SlugRoute,
  ProsjektMlSlugRoute: ProsjektMlSlugRoute,
  PythonVisualizerRoute: PythonVisualizerRoute,
  PythonKapNrRoute: PythonKapNrRoute,
  PythonKapIndexRoute: PythonKapIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
