/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VizLesjonRouteImport } from './routes/viz-lesjon'
import { Route as VisualiseringerRouteImport } from './routes/visualiseringer'
import { Route as VenvDrillRouteImport } from './routes/venv-drill'
import { Route as StackRouteImport } from './routes/stack'
import { Route as SporRouteImport } from './routes/spor'
import { Route as SkillTreRouteImport } from './routes/skill-tre'
import { Route as RepetisjonRouteImport } from './routes/repetisjon'
import { Route as PythonRouteImport } from './routes/python'
import { Route as ProsjektRouteImport } from './routes/prosjekt'
import { Route as PredictRouteImport } from './routes/predict'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as OvRouteImport } from './routes/ov'
import { Route as MiniKursRouteImport } from './routes/mini-kurs'
import { Route as MacDrillRouteImport } from './routes/mac-drill'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LarRouteImport } from './routes/lar'
import { Route as KursRouteImport } from './routes/kurs'
import { Route as KonsollRouteImport } from './routes/konsoll'
import { Route as JoinsRouteImport } from './routes/joins'
import { Route as IllustrationsRouteImport } from './routes/illustrations'
import { Route as GitDrillRouteImport } from './routes/git-drill'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as ErTegnerRouteImport } from './routes/er-tegner'
import { Route as EksamenRouteImport } from './routes/eksamen'
import { Route as DragRouteImport } from './routes/drag'
import { Route as DiagnoseRouteImport } from './routes/diagnose'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VizLesjonIndexRouteImport } from './routes/viz-lesjon.index'
import { Route as StackIndexRouteImport } from './routes/stack.index'
import { Route as SporIndexRouteImport } from './routes/spor.index'
import { Route as MiniKursIndexRouteImport } from './routes/mini-kurs.index'
import { Route as EksamenIndexRouteImport } from './routes/eksamen.index'
import { Route as VizLesjonSlugRouteImport } from './routes/viz-lesjon.$slug'
import { Route as StackSlugRouteImport } from './routes/stack.$slug'
import { Route as SporSlugRouteImport } from './routes/spor.$slug'
import { Route as PythonVisualizerRouteImport } from './routes/python_.visualizer'
import { Route as PythonKjerneRouteImport } from './routes/python_.kjerne'
import { Route as PythonChar91_figuresChar93RouteImport } from './routes/python_.[_figures]'
import { Route as ProsjektMlSlugRouteImport } from './routes/prosjekt-ml.$slug'
import { Route as PortfolioDte2602SlugRouteImport } from './routes/portfolio-dte2602.$slug'
import { Route as MiniKursSlugRouteImport } from './routes/mini-kurs.$slug'
import { Route as EksamenTreningRouteImport } from './routes/eksamen.trening'
import { Route as Dte2507PcapRouteImport } from './routes/dte2507.pcap'
import { Route as Dte2505ShellDrillRouteImport } from './routes/dte2505.shell-drill'
import { Route as DrillChar91_demoChar93RouteImport } from './routes/drill.[_demo]'
import { Route as PythonKapIndexRouteImport } from './routes/python_.kap.index'
import { Route as PythonKapNrRouteImport } from './routes/python_.kap.$nr'
import { Route as PythonIdeNrRouteImport } from './routes/python_.ide.$nr'

const VizLesjonRoute = VizLesjonRouteImport.update({
  id: '/viz-lesjon',
  path: '/viz-lesjon',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualiseringerRoute = VisualiseringerRouteImport.update({
  id: '/visualiseringer',
  path: '/visualiseringer',
  getParentRoute: () => rootRouteImport,
} as any)
const VenvDrillRoute = VenvDrillRouteImport.update({
  id: '/venv-drill',
  path: '/venv-drill',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const SporRoute = SporRouteImport.update({
  id: '/spor',
  path: '/spor',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillTreRoute = SkillTreRouteImport.update({
  id: '/skill-tre',
  path: '/skill-tre',
  getParentRoute: () => rootRouteImport,
} as any)
const RepetisjonRoute = RepetisjonRouteImport.update({
  id: '/repetisjon',
  path: '/repetisjon',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonRoute = PythonRouteImport.update({
  id: '/python',
  path: '/python',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsjektRoute = ProsjektRouteImport.update({
  id: '/prosjekt',
  path: '/prosjekt',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictRoute = PredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const OvRoute = OvRouteImport.update({
  id: '/ov',
  path: '/ov',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniKursRoute = MiniKursRouteImport.update({
  id: '/mini-kurs',
  path: '/mini-kurs',
  getParentRoute: () => rootRouteImport,
} as any)
const MacDrillRoute = MacDrillRouteImport.update({
  id: '/mac-drill',
  path: '/mac-drill',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LarRoute = LarRouteImport.update({
  id: '/lar',
  path: '/lar',
  getParentRoute: () => rootRouteImport,
} as any)
const KursRoute = KursRouteImport.update({
  id: '/kurs',
  path: '/kurs',
  getParentRoute: () => rootRouteImport,
} as any)
const KonsollRoute = KonsollRouteImport.update({
  id: '/konsoll',
  path: '/konsoll',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinsRoute = JoinsRouteImport.update({
  id: '/joins',
  path: '/joins',
  getParentRoute: () => rootRouteImport,
} as any)
const IllustrationsRoute = IllustrationsRouteImport.update({
  id: '/illustrations',
  path: '/illustrations',
  getParentRoute: () => rootRouteImport,
} as any)
const GitDrillRoute = GitDrillRouteImport.update({
  id: '/git-drill',
  path: '/git-drill',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const ErTegnerRoute = ErTegnerRouteImport.update({
  id: '/er-tegner',
  path: '/er-tegner',
  getParentRoute: () => rootRouteImport,
} as any)
const EksamenRoute = EksamenRouteImport.update({
  id: '/eksamen',
  path: '/eksamen',
  getParentRoute: () => rootRouteImport,
} as any)
const DragRoute = DragRouteImport.update({
  id: '/drag',
  path: '/drag',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnoseRoute = DiagnoseRouteImport.update({
  id: '/diagnose',
  path: '/diagnose',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VizLesjonIndexRoute = VizLesjonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VizLesjonRoute,
} as any)
const StackIndexRoute = StackIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StackRoute,
} as any)
const SporIndexRoute = SporIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SporRoute,
} as any)
const MiniKursIndexRoute = MiniKursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MiniKursRoute,
} as any)
const EksamenIndexRoute = EksamenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EksamenRoute,
} as any)
const VizLesjonSlugRoute = VizLesjonSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VizLesjonRoute,
} as any)
const StackSlugRoute = StackSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StackRoute,
} as any)
const SporSlugRoute = SporSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SporRoute,
} as any)
const PythonVisualizerRoute = PythonVisualizerRouteImport.update({
  id: '/python_/visualizer',
  path: '/python/visualizer',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonKjerneRoute = PythonKjerneRouteImport.update({
  id: '/python_/kjerne',
  path: '/python/kjerne',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonChar91_figuresChar93Route =
  PythonChar91_figuresChar93RouteImport.update({
    id: '/python_/_figures',
    path: '/python/_figures',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProsjektMlSlugRoute = ProsjektMlSlugRouteImport.update({
  id: '/prosjekt-ml/$slug',
  path: '/prosjekt-ml/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioDte2602SlugRoute = PortfolioDte2602SlugRouteImport.update({
  id: '/portfolio-dte2602/$slug',
  path: '/portfolio-dte2602/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniKursSlugRoute = MiniKursSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MiniKursRoute,
} as any)
const EksamenTreningRoute = EksamenTreningRouteImport.update({
  id: '/trening',
  path: '/trening',
  getParentRoute: () => EksamenRoute,
} as any)
const Dte2507PcapRoute = Dte2507PcapRouteImport.update({
  id: '/dte2507/pcap',
  path: '/dte2507/pcap',
  getParentRoute: () => rootRouteImport,
} as any)
const Dte2505ShellDrillRoute = Dte2505ShellDrillRouteImport.update({
  id: '/dte2505/shell-drill',
  path: '/dte2505/shell-drill',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillChar91_demoChar93Route = DrillChar91_demoChar93RouteImport.update({
  id: '/drill/_demo',
  path: '/drill/_demo',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonKapIndexRoute = PythonKapIndexRouteImport.update({
  id: '/python_/kap/',
  path: '/python/kap/',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonKapNrRoute = PythonKapNrRouteImport.update({
  id: '/python_/kap/$nr',
  path: '/python/kap/$nr',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonIdeNrRoute = PythonIdeNrRouteImport.update({
  id: '/python_/ide/$nr',
  path: '/python/ide/$nr',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/diagnose': typeof DiagnoseRoute
  '/drag': typeof DragRoute
  '/eksamen': typeof EksamenRouteWithChildren
  '/er-tegner': typeof ErTegnerRoute
  '/exam': typeof ExamRoute
  '/git-drill': typeof GitDrillRoute
  '/illustrations': typeof IllustrationsRoute
  '/joins': typeof JoinsRoute
  '/konsoll': typeof KonsollRoute
  '/kurs': typeof KursRoute
  '/lar': typeof LarRoute
  '/learn': typeof LearnRoute
  '/mac-drill': typeof MacDrillRoute
  '/mini-kurs': typeof MiniKursRouteWithChildren
  '/ov': typeof OvRoute
  '/practice': typeof PracticeRoute
  '/predict': typeof PredictRoute
  '/prosjekt': typeof ProsjektRoute
  '/python': typeof PythonRoute
  '/repetisjon': typeof RepetisjonRoute
  '/skill-tre': typeof SkillTreRoute
  '/spor': typeof SporRouteWithChildren
  '/stack': typeof StackRouteWithChildren
  '/venv-drill': typeof VenvDrillRoute
  '/visualiseringer': typeof VisualiseringerRoute
  '/viz-lesjon': typeof VizLesjonRouteWithChildren
  '/drill/_demo': typeof DrillChar91_demoChar93Route
  '/dte2505/shell-drill': typeof Dte2505ShellDrillRoute
  '/dte2507/pcap': typeof Dte2507PcapRoute
  '/eksamen/trening': typeof EksamenTreningRoute
  '/mini-kurs/$slug': typeof MiniKursSlugRoute
  '/portfolio-dte2602/$slug': typeof PortfolioDte2602SlugRoute
  '/prosjekt-ml/$slug': typeof ProsjektMlSlugRoute
  '/python/_figures': typeof PythonChar91_figuresChar93Route
  '/python/kjerne': typeof PythonKjerneRoute
  '/python/visualizer': typeof PythonVisualizerRoute
  '/spor/$slug': typeof SporSlugRoute
  '/stack/$slug': typeof StackSlugRoute
  '/viz-lesjon/$slug': typeof VizLesjonSlugRoute
  '/eksamen/': typeof EksamenIndexRoute
  '/mini-kurs/': typeof MiniKursIndexRoute
  '/spor/': typeof SporIndexRoute
  '/stack/': typeof StackIndexRoute
  '/viz-lesjon/': typeof VizLesjonIndexRoute
  '/python/ide/$nr': typeof PythonIdeNrRoute
  '/python/kap/$nr': typeof PythonKapNrRoute
  '/python/kap/': typeof PythonKapIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/diagnose': typeof DiagnoseRoute
  '/drag': typeof DragRoute
  '/er-tegner': typeof ErTegnerRoute
  '/exam': typeof ExamRoute
  '/git-drill': typeof GitDrillRoute
  '/illustrations': typeof IllustrationsRoute
  '/joins': typeof JoinsRoute
  '/konsoll': typeof KonsollRoute
  '/kurs': typeof KursRoute
  '/lar': typeof LarRoute
  '/learn': typeof LearnRoute
  '/mac-drill': typeof MacDrillRoute
  '/ov': typeof OvRoute
  '/practice': typeof PracticeRoute
  '/predict': typeof PredictRoute
  '/prosjekt': typeof ProsjektRoute
  '/python': typeof PythonRoute
  '/repetisjon': typeof RepetisjonRoute
  '/skill-tre': typeof SkillTreRoute
  '/venv-drill': typeof VenvDrillRoute
  '/visualiseringer': typeof VisualiseringerRoute
  '/drill/_demo': typeof DrillChar91_demoChar93Route
  '/dte2505/shell-drill': typeof Dte2505ShellDrillRoute
  '/dte2507/pcap': typeof Dte2507PcapRoute
  '/eksamen/trening': typeof EksamenTreningRoute
  '/mini-kurs/$slug': typeof MiniKursSlugRoute
  '/portfolio-dte2602/$slug': typeof PortfolioDte2602SlugRoute
  '/prosjekt-ml/$slug': typeof ProsjektMlSlugRoute
  '/python/_figures': typeof PythonChar91_figuresChar93Route
  '/python/kjerne': typeof PythonKjerneRoute
  '/python/visualizer': typeof PythonVisualizerRoute
  '/spor/$slug': typeof SporSlugRoute
  '/stack/$slug': typeof StackSlugRoute
  '/viz-lesjon/$slug': typeof VizLesjonSlugRoute
  '/eksamen': typeof EksamenIndexRoute
  '/mini-kurs': typeof MiniKursIndexRoute
  '/spor': typeof SporIndexRoute
  '/stack': typeof StackIndexRoute
  '/viz-lesjon': typeof VizLesjonIndexRoute
  '/python/ide/$nr': typeof PythonIdeNrRoute
  '/python/kap/$nr': typeof PythonKapNrRoute
  '/python/kap': typeof PythonKapIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/diagnose': typeof DiagnoseRoute
  '/drag': typeof DragRoute
  '/eksamen': typeof EksamenRouteWithChildren
  '/er-tegner': typeof ErTegnerRoute
  '/exam': typeof ExamRoute
  '/git-drill': typeof GitDrillRoute
  '/illustrations': typeof IllustrationsRoute
  '/joins': typeof JoinsRoute
  '/konsoll': typeof KonsollRoute
  '/kurs': typeof KursRoute
  '/lar': typeof LarRoute
  '/learn': typeof LearnRoute
  '/mac-drill': typeof MacDrillRoute
  '/mini-kurs': typeof MiniKursRouteWithChildren
  '/ov': typeof OvRoute
  '/practice': typeof PracticeRoute
  '/predict': typeof PredictRoute
  '/prosjekt': typeof ProsjektRoute
  '/python': typeof PythonRoute
  '/repetisjon': typeof RepetisjonRoute
  '/skill-tre': typeof SkillTreRoute
  '/spor': typeof SporRouteWithChildren
  '/stack': typeof StackRouteWithChildren
  '/venv-drill': typeof VenvDrillRoute
  '/visualiseringer': typeof VisualiseringerRoute
  '/viz-lesjon': typeof VizLesjonRouteWithChildren
  '/drill/_demo': typeof DrillChar91_demoChar93Route
  '/dte2505/shell-drill': typeof Dte2505ShellDrillRoute
  '/dte2507/pcap': typeof Dte2507PcapRoute
  '/eksamen/trening': typeof EksamenTreningRoute
  '/mini-kurs/$slug': typeof MiniKursSlugRoute
  '/portfolio-dte2602/$slug': typeof PortfolioDte2602SlugRoute
  '/prosjekt-ml/$slug': typeof ProsjektMlSlugRoute
  '/python_/_figures': typeof PythonChar91_figuresChar93Route
  '/python_/kjerne': typeof PythonKjerneRoute
  '/python_/visualizer': typeof PythonVisualizerRoute
  '/spor/$slug': typeof SporSlugRoute
  '/stack/$slug': typeof StackSlugRoute
  '/viz-lesjon/$slug': typeof VizLesjonSlugRoute
  '/eksamen/': typeof EksamenIndexRoute
  '/mini-kurs/': typeof MiniKursIndexRoute
  '/spor/': typeof SporIndexRoute
  '/stack/': typeof StackIndexRoute
  '/viz-lesjon/': typeof VizLesjonIndexRoute
  '/python_/ide/$nr': typeof PythonIdeNrRoute
  '/python_/kap/$nr': typeof PythonKapNrRoute
  '/python_/kap/': typeof PythonKapIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cards'
    | '/dashboard'
    | '/diagnose'
    | '/drag'
    | '/eksamen'
    | '/er-tegner'
    | '/exam'
    | '/git-drill'
    | '/illustrations'
    | '/joins'
    | '/konsoll'
    | '/kurs'
    | '/lar'
    | '/learn'
    | '/mac-drill'
    | '/mini-kurs'
    | '/ov'
    | '/practice'
    | '/predict'
    | '/prosjekt'
    | '/python'
    | '/repetisjon'
    | '/skill-tre'
    | '/spor'
    | '/stack'
    | '/venv-drill'
    | '/visualiseringer'
    | '/viz-lesjon'
    | '/drill/_demo'
    | '/dte2505/shell-drill'
    | '/dte2507/pcap'
    | '/eksamen/trening'
    | '/mini-kurs/$slug'
    | '/portfolio-dte2602/$slug'
    | '/prosjekt-ml/$slug'
    | '/python/_figures'
    | '/python/kjerne'
    | '/python/visualizer'
    | '/spor/$slug'
    | '/stack/$slug'
    | '/viz-lesjon/$slug'
    | '/eksamen/'
    | '/mini-kurs/'
    | '/spor/'
    | '/stack/'
    | '/viz-lesjon/'
    | '/python/ide/$nr'
    | '/python/kap/$nr'
    | '/python/kap/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cards'
    | '/dashboard'
    | '/diagnose'
    | '/drag'
    | '/er-tegner'
    | '/exam'
    | '/git-drill'
    | '/illustrations'
    | '/joins'
    | '/konsoll'
    | '/kurs'
    | '/lar'
    | '/learn'
    | '/mac-drill'
    | '/ov'
    | '/practice'
    | '/predict'
    | '/prosjekt'
    | '/python'
    | '/repetisjon'
    | '/skill-tre'
    | '/venv-drill'
    | '/visualiseringer'
    | '/drill/_demo'
    | '/dte2505/shell-drill'
    | '/dte2507/pcap'
    | '/eksamen/trening'
    | '/mini-kurs/$slug'
    | '/portfolio-dte2602/$slug'
    | '/prosjekt-ml/$slug'
    | '/python/_figures'
    | '/python/kjerne'
    | '/python/visualizer'
    | '/spor/$slug'
    | '/stack/$slug'
    | '/viz-lesjon/$slug'
    | '/eksamen'
    | '/mini-kurs'
    | '/spor'
    | '/stack'
    | '/viz-lesjon'
    | '/python/ide/$nr'
    | '/python/kap/$nr'
    | '/python/kap'
  id:
    | '__root__'
    | '/'
    | '/cards'
    | '/dashboard'
    | '/diagnose'
    | '/drag'
    | '/eksamen'
    | '/er-tegner'
    | '/exam'
    | '/git-drill'
    | '/illustrations'
    | '/joins'
    | '/konsoll'
    | '/kurs'
    | '/lar'
    | '/learn'
    | '/mac-drill'
    | '/mini-kurs'
    | '/ov'
    | '/practice'
    | '/predict'
    | '/prosjekt'
    | '/python'
    | '/repetisjon'
    | '/skill-tre'
    | '/spor'
    | '/stack'
    | '/venv-drill'
    | '/visualiseringer'
    | '/viz-lesjon'
    | '/drill/_demo'
    | '/dte2505/shell-drill'
    | '/dte2507/pcap'
    | '/eksamen/trening'
    | '/mini-kurs/$slug'
    | '/portfolio-dte2602/$slug'
    | '/prosjekt-ml/$slug'
    | '/python_/_figures'
    | '/python_/kjerne'
    | '/python_/visualizer'
    | '/spor/$slug'
    | '/stack/$slug'
    | '/viz-lesjon/$slug'
    | '/eksamen/'
    | '/mini-kurs/'
    | '/spor/'
    | '/stack/'
    | '/viz-lesjon/'
    | '/python_/ide/$nr'
    | '/python_/kap/$nr'
    | '/python_/kap/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsRoute: typeof CardsRoute
  DashboardRoute: typeof DashboardRoute
  DiagnoseRoute: typeof DiagnoseRoute
  DragRoute: typeof DragRoute
  EksamenRoute: typeof EksamenRouteWithChildren
  ErTegnerRoute: typeof ErTegnerRoute
  ExamRoute: typeof ExamRoute
  GitDrillRoute: typeof GitDrillRoute
  IllustrationsRoute: typeof IllustrationsRoute
  JoinsRoute: typeof JoinsRoute
  KonsollRoute: typeof KonsollRoute
  KursRoute: typeof KursRoute
  LarRoute: typeof LarRoute
  LearnRoute: typeof LearnRoute
  MacDrillRoute: typeof MacDrillRoute
  MiniKursRoute: typeof MiniKursRouteWithChildren
  OvRoute: typeof OvRoute
  PracticeRoute: typeof PracticeRoute
  PredictRoute: typeof PredictRoute
  ProsjektRoute: typeof ProsjektRoute
  PythonRoute: typeof PythonRoute
  RepetisjonRoute: typeof RepetisjonRoute
  SkillTreRoute: typeof SkillTreRoute
  SporRoute: typeof SporRouteWithChildren
  StackRoute: typeof StackRouteWithChildren
  VenvDrillRoute: typeof VenvDrillRoute
  VisualiseringerRoute: typeof VisualiseringerRoute
  VizLesjonRoute: typeof VizLesjonRouteWithChildren
  DrillChar91_demoChar93Route: typeof DrillChar91_demoChar93Route
  Dte2505ShellDrillRoute: typeof Dte2505ShellDrillRoute
  Dte2507PcapRoute: typeof Dte2507PcapRoute
  PortfolioDte2602SlugRoute: typeof PortfolioDte2602SlugRoute
  ProsjektMlSlugRoute: typeof ProsjektMlSlugRoute
  PythonChar91_figuresChar93Route: typeof PythonChar91_figuresChar93Route
  PythonKjerneRoute: typeof PythonKjerneRoute
  PythonVisualizerRoute: typeof PythonVisualizerRoute
  PythonIdeNrRoute: typeof PythonIdeNrRoute
  PythonKapNrRoute: typeof PythonKapNrRoute
  PythonKapIndexRoute: typeof PythonKapIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viz-lesjon': {
      id: '/viz-lesjon'
      path: '/viz-lesjon'
      fullPath: '/viz-lesjon'
      preLoaderRoute: typeof VizLesjonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualiseringer': {
      id: '/visualiseringer'
      path: '/visualiseringer'
      fullPath: '/visualiseringer'
      preLoaderRoute: typeof VisualiseringerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venv-drill': {
      id: '/venv-drill'
      path: '/venv-drill'
      fullPath: '/venv-drill'
      preLoaderRoute: typeof VenvDrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spor': {
      id: '/spor'
      path: '/spor'
      fullPath: '/spor'
      preLoaderRoute: typeof SporRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-tre': {
      id: '/skill-tre'
      path: '/skill-tre'
      fullPath: '/skill-tre'
      preLoaderRoute: typeof SkillTreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repetisjon': {
      id: '/repetisjon'
      path: '/repetisjon'
      fullPath: '/repetisjon'
      preLoaderRoute: typeof RepetisjonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python': {
      id: '/python'
      path: '/python'
      fullPath: '/python'
      preLoaderRoute: typeof PythonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prosjekt': {
      id: '/prosjekt'
      path: '/prosjekt'
      fullPath: '/prosjekt'
      preLoaderRoute: typeof ProsjektRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predict': {
      id: '/predict'
      path: '/predict'
      fullPath: '/predict'
      preLoaderRoute: typeof PredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ov': {
      id: '/ov'
      path: '/ov'
      fullPath: '/ov'
      preLoaderRoute: typeof OvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mini-kurs': {
      id: '/mini-kurs'
      path: '/mini-kurs'
      fullPath: '/mini-kurs'
      preLoaderRoute: typeof MiniKursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mac-drill': {
      id: '/mac-drill'
      path: '/mac-drill'
      fullPath: '/mac-drill'
      preLoaderRoute: typeof MacDrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lar': {
      id: '/lar'
      path: '/lar'
      fullPath: '/lar'
      preLoaderRoute: typeof LarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurs': {
      id: '/kurs'
      path: '/kurs'
      fullPath: '/kurs'
      preLoaderRoute: typeof KursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konsoll': {
      id: '/konsoll'
      path: '/konsoll'
      fullPath: '/konsoll'
      preLoaderRoute: typeof KonsollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joins': {
      id: '/joins'
      path: '/joins'
      fullPath: '/joins'
      preLoaderRoute: typeof JoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/illustrations': {
      id: '/illustrations'
      path: '/illustrations'
      fullPath: '/illustrations'
      preLoaderRoute: typeof IllustrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/git-drill': {
      id: '/git-drill'
      path: '/git-drill'
      fullPath: '/git-drill'
      preLoaderRoute: typeof GitDrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/er-tegner': {
      id: '/er-tegner'
      path: '/er-tegner'
      fullPath: '/er-tegner'
      preLoaderRoute: typeof ErTegnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eksamen': {
      id: '/eksamen'
      path: '/eksamen'
      fullPath: '/eksamen'
      preLoaderRoute: typeof EksamenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drag': {
      id: '/drag'
      path: '/drag'
      fullPath: '/drag'
      preLoaderRoute: typeof DragRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnose': {
      id: '/diagnose'
      path: '/diagnose'
      fullPath: '/diagnose'
      preLoaderRoute: typeof DiagnoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viz-lesjon/': {
      id: '/viz-lesjon/'
      path: '/'
      fullPath: '/viz-lesjon/'
      preLoaderRoute: typeof VizLesjonIndexRouteImport
      parentRoute: typeof VizLesjonRoute
    }
    '/stack/': {
      id: '/stack/'
      path: '/'
      fullPath: '/stack/'
      preLoaderRoute: typeof StackIndexRouteImport
      parentRoute: typeof StackRoute
    }
    '/spor/': {
      id: '/spor/'
      path: '/'
      fullPath: '/spor/'
      preLoaderRoute: typeof SporIndexRouteImport
      parentRoute: typeof SporRoute
    }
    '/mini-kurs/': {
      id: '/mini-kurs/'
      path: '/'
      fullPath: '/mini-kurs/'
      preLoaderRoute: typeof MiniKursIndexRouteImport
      parentRoute: typeof MiniKursRoute
    }
    '/eksamen/': {
      id: '/eksamen/'
      path: '/'
      fullPath: '/eksamen/'
      preLoaderRoute: typeof EksamenIndexRouteImport
      parentRoute: typeof EksamenRoute
    }
    '/viz-lesjon/$slug': {
      id: '/viz-lesjon/$slug'
      path: '/$slug'
      fullPath: '/viz-lesjon/$slug'
      preLoaderRoute: typeof VizLesjonSlugRouteImport
      parentRoute: typeof VizLesjonRoute
    }
    '/stack/$slug': {
      id: '/stack/$slug'
      path: '/$slug'
      fullPath: '/stack/$slug'
      preLoaderRoute: typeof StackSlugRouteImport
      parentRoute: typeof StackRoute
    }
    '/spor/$slug': {
      id: '/spor/$slug'
      path: '/$slug'
      fullPath: '/spor/$slug'
      preLoaderRoute: typeof SporSlugRouteImport
      parentRoute: typeof SporRoute
    }
    '/python_/visualizer': {
      id: '/python_/visualizer'
      path: '/python/visualizer'
      fullPath: '/python/visualizer'
      preLoaderRoute: typeof PythonVisualizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python_/kjerne': {
      id: '/python_/kjerne'
      path: '/python/kjerne'
      fullPath: '/python/kjerne'
      preLoaderRoute: typeof PythonKjerneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python_/_figures': {
      id: '/python_/_figures'
      path: '/python/_figures'
      fullPath: '/python/_figures'
      preLoaderRoute: typeof PythonChar91_figuresChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prosjekt-ml/$slug': {
      id: '/prosjekt-ml/$slug'
      path: '/prosjekt-ml/$slug'
      fullPath: '/prosjekt-ml/$slug'
      preLoaderRoute: typeof ProsjektMlSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-dte2602/$slug': {
      id: '/portfolio-dte2602/$slug'
      path: '/portfolio-dte2602/$slug'
      fullPath: '/portfolio-dte2602/$slug'
      preLoaderRoute: typeof PortfolioDte2602SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mini-kurs/$slug': {
      id: '/mini-kurs/$slug'
      path: '/$slug'
      fullPath: '/mini-kurs/$slug'
      preLoaderRoute: typeof MiniKursSlugRouteImport
      parentRoute: typeof MiniKursRoute
    }
    '/eksamen/trening': {
      id: '/eksamen/trening'
      path: '/trening'
      fullPath: '/eksamen/trening'
      preLoaderRoute: typeof EksamenTreningRouteImport
      parentRoute: typeof EksamenRoute
    }
    '/dte2507/pcap': {
      id: '/dte2507/pcap'
      path: '/dte2507/pcap'
      fullPath: '/dte2507/pcap'
      preLoaderRoute: typeof Dte2507PcapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dte2505/shell-drill': {
      id: '/dte2505/shell-drill'
      path: '/dte2505/shell-drill'
      fullPath: '/dte2505/shell-drill'
      preLoaderRoute: typeof Dte2505ShellDrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill/_demo': {
      id: '/drill/_demo'
      path: '/drill/_demo'
      fullPath: '/drill/_demo'
      preLoaderRoute: typeof DrillChar91_demoChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python_/kap/': {
      id: '/python_/kap/'
      path: '/python/kap'
      fullPath: '/python/kap/'
      preLoaderRoute: typeof PythonKapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python_/kap/$nr': {
      id: '/python_/kap/$nr'
      path: '/python/kap/$nr'
      fullPath: '/python/kap/$nr'
      preLoaderRoute: typeof PythonKapNrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python_/ide/$nr': {
      id: '/python_/ide/$nr'
      path: '/python/ide/$nr'
      fullPath: '/python/ide/$nr'
      preLoaderRoute: typeof PythonIdeNrRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EksamenRouteChildren {
  EksamenTreningRoute: typeof EksamenTreningRoute
  EksamenIndexRoute: typeof EksamenIndexRoute
}

const EksamenRouteChildren: EksamenRouteChildren = {
  EksamenTreningRoute: EksamenTreningRoute,
  EksamenIndexRoute: EksamenIndexRoute,
}

const EksamenRouteWithChildren =
  EksamenRoute._addFileChildren(EksamenRouteChildren)

interface MiniKursRouteChildren {
  MiniKursSlugRoute: typeof MiniKursSlugRoute
  MiniKursIndexRoute: typeof MiniKursIndexRoute
}

const MiniKursRouteChildren: MiniKursRouteChildren = {
  MiniKursSlugRoute: MiniKursSlugRoute,
  MiniKursIndexRoute: MiniKursIndexRoute,
}

const MiniKursRouteWithChildren = MiniKursRoute._addFileChildren(
  MiniKursRouteChildren,
)

interface SporRouteChildren {
  SporSlugRoute: typeof SporSlugRoute
  SporIndexRoute: typeof SporIndexRoute
}

const SporRouteChildren: SporRouteChildren = {
  SporSlugRoute: SporSlugRoute,
  SporIndexRoute: SporIndexRoute,
}

const SporRouteWithChildren = SporRoute._addFileChildren(SporRouteChildren)

interface StackRouteChildren {
  StackSlugRoute: typeof StackSlugRoute
  StackIndexRoute: typeof StackIndexRoute
}

const StackRouteChildren: StackRouteChildren = {
  StackSlugRoute: StackSlugRoute,
  StackIndexRoute: StackIndexRoute,
}

const StackRouteWithChildren = StackRoute._addFileChildren(StackRouteChildren)

interface VizLesjonRouteChildren {
  VizLesjonSlugRoute: typeof VizLesjonSlugRoute
  VizLesjonIndexRoute: typeof VizLesjonIndexRoute
}

const VizLesjonRouteChildren: VizLesjonRouteChildren = {
  VizLesjonSlugRoute: VizLesjonSlugRoute,
  VizLesjonIndexRoute: VizLesjonIndexRoute,
}

const VizLesjonRouteWithChildren = VizLesjonRoute._addFileChildren(
  VizLesjonRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsRoute: CardsRoute,
  DashboardRoute: DashboardRoute,
  DiagnoseRoute: DiagnoseRoute,
  DragRoute: DragRoute,
  EksamenRoute: EksamenRouteWithChildren,
  ErTegnerRoute: ErTegnerRoute,
  ExamRoute: ExamRoute,
  GitDrillRoute: GitDrillRoute,
  IllustrationsRoute: IllustrationsRoute,
  JoinsRoute: JoinsRoute,
  KonsollRoute: KonsollRoute,
  KursRoute: KursRoute,
  LarRoute: LarRoute,
  LearnRoute: LearnRoute,
  MacDrillRoute: MacDrillRoute,
  MiniKursRoute: MiniKursRouteWithChildren,
  OvRoute: OvRoute,
  PracticeRoute: PracticeRoute,
  PredictRoute: PredictRoute,
  ProsjektRoute: ProsjektRoute,
  PythonRoute: PythonRoute,
  RepetisjonRoute: RepetisjonRoute,
  SkillTreRoute: SkillTreRoute,
  SporRoute: SporRouteWithChildren,
  StackRoute: StackRouteWithChildren,
  VenvDrillRoute: VenvDrillRoute,
  VisualiseringerRoute: VisualiseringerRoute,
  VizLesjonRoute: VizLesjonRouteWithChildren,
  DrillChar91_demoChar93Route: DrillChar91_demoChar93Route,
  Dte2505ShellDrillRoute: Dte2505ShellDrillRoute,
  Dte2507PcapRoute: Dte2507PcapRoute,
  PortfolioDte2602SlugRoute: PortfolioDte2602SlugRoute,
  ProsjektMlSlugRoute: ProsjektMlSlugRoute,
  PythonChar91_figuresChar93Route: PythonChar91_figuresChar93Route,
  PythonKjerneRoute: PythonKjerneRoute,
  PythonVisualizerRoute: PythonVisualizerRoute,
  PythonIdeNrRoute: PythonIdeNrRoute,
  PythonKapNrRoute: PythonKapNrRoute,
  PythonKapIndexRoute: PythonKapIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
